"""Calculate statistics to determine the surface brightness and spatial scale of the background variations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/background.ipynb.

# %% auto 0
__all__ = ['sub_bkg', 'aperture_stats', 'stats_versus_size', 'background_stats_plot', 'measure']

# %% ../../nbs/euclid/background.ipynb 2
import os

import matplotlib.pyplot as plt
import numpy as np

from astropy.io import fits
from astropy import table
from astropy.convolution import convolve, TrapezoidDisk2DKernel
from matplotlib.ticker import FuncFormatter, NullLocator
from matplotlib import patheffects as pe

from photutils.aperture import (
    CircularAperture,
    CircularAnnulus,
    RectangularAperture,
    RectangularAnnulus,
    ApertureStats,
)
from photutils.background import Background2D
from tqdm import tqdm

from ..mask import fast_mask, plot_mask

# %% ../../nbs/euclid/background.ipynb 4
def sub_bkg(
    img,  # input image
    dq_mask=None,  # data quality mask for bad pixels
    obj_mask="fast_mask",  # object mask; can be a callable function or an array
    mesh_size=None,  # mesh size for background modeling; default to 1x1 mesh if not specified
    **kwargs,  # additional arguments for Background2D
):
    """model background and subtract it from the input image. Optionally building an object mask if the user provides a function name instead of an array via `obj_mask`."""
    img = np.asarray(img)
    # check if need to build object mask
    if isinstance(obj_mask, str):
        # determine if obj_mask is a callable function
        if obj_mask in globals() and callable(globals()[obj_mask]):
            obj_mask = globals()[obj_mask]
        elif obj_mask in locals() and callable(locals()[obj_mask]):
            obj_mask = locals()[obj_mask]
        else:
            raise ValueError(f"{obj_mask} is not a valid function name")
        match obj_mask.__name__:
            case "fast_mask":
                obj_mask, _ = obj_mask(
                    img,
                    estimate_background=True,
                )
            case _:
                obj_mask = obj_mask(img)
    else:
        obj_mask = np.asarray(obj_mask).astype(bool)
    # check if the shape matches
    if obj_mask.shape != img.shape:
        raise ValueError(
            "The shape of the object mask does not match that of the input image."
        )
    # combine the dq_mask and obj_mask
    if dq_mask is not None:
        dq_mask = np.asarray(dq_mask).astype(bool)
        if dq_mask.shape != img.shape:
            raise ValueError(
                "The shape of the data quality mask does not match that of the input image."
            )
        mask = dq_mask | obj_mask
    else:
        mask = obj_mask
    # default 1x1 mesh
    if mesh_size is None:
        mesh_size = img.shape[0], img.shape[1]
    bg = Background2D(
        img,
        mesh_size,
        mask=mask,
        **kwargs,
    )
    return img - bg.background

# %% ../../nbs/euclid/background.ipynb 5
def aperture_stats(
    data,
    mask,
    n_apertures,
    sqrt_n_pix,
    aperture_shape,
    annular_thickness=None,
    n_pix_tolerance=0.1,
):
    if aperture_shape == "square":
        outer_size = sqrt_n_pix
    if aperture_shape == "circle":
        outer_size = sqrt_n_pix * 2 / np.sqrt(np.pi)

    # adjust aperture sizes to account, on average, for masked pixels
    unmasked_frac = 1 - mask.sum() / mask.size
    outer_size /= np.sqrt(unmasked_frac)

    annulus = annular_thickness is not None and annular_thickness < 1
    if sqrt_n_pix < 3:
        # does not make sense to use an annulus for small numbers of pixels
        annulus = False

    if annulus:
        outer_size = outer_size / np.sqrt(1 - (1 - annular_thickness) ** 2)
        inner_size = (1 - annular_thickness) * outer_size
    else:
        inner_size = 0

    x = np.random.uniform(outer_size / 2, data.shape[1] - outer_size / 2, n_apertures)
    y = np.random.uniform(outer_size / 2, data.shape[0] - outer_size / 2, n_apertures)
    positions = np.transpose(np.vstack((x, y)))

    if aperture_shape == "square":
        if annulus:
            ap = RectangularAnnulus(
                positions,
                w_in=inner_size,
                w_out=outer_size,
                h_in=inner_size,
                h_out=outer_size,
            )
        else:
            ap = RectangularAperture(positions, w=outer_size, h=outer_size)
    elif aperture_shape == "circle":
        if annulus:
            ap = CircularAnnulus(positions, r_in=inner_size / 2, r_out=outer_size / 2)
        else:
            ap = CircularAperture(positions, r=outer_size / 2)

    stats = ApertureStats(data, ap, mask=mask, sum_method="center")
    stats = stats.to_table(columns=("sum_aper_area", "mean", "median"))
    n_pix = sqrt_n_pix**2
    achieved_n_pix = stats["sum_aper_area"].value
    ok = abs(achieved_n_pix - n_pix) / n_pix < n_pix_tolerance
    n_ok = ok.sum()
    stats = stats[ok]
    std_mean = np.std(stats["mean"])
    err_std_mean = std_mean / np.sqrt(2 * n_ok - 2)
    std_median = np.std(stats["median"])
    err_std_median = std_median / np.sqrt(2 * n_ok - 2)
    results = dict(
        sqrt_n_pix=sqrt_n_pix,
        std_mean=std_mean,
        err_std_mean=err_std_mean,
        std_median=std_median,
        err_std_median=err_std_median,
        n_ok=n_ok,
        outer_size=outer_size,
    )
    return results

# %% ../../nbs/euclid/background.ipynb 6
def stats_versus_size(
    data,
    mask,
    n_apertures,
    max_sqrt_n_pix,
    aperture_shape,
    annular_thickness=None,
    n_pix_tolerance=0.1,
    n_steps=20,
):
    sqrt_n_pix_list = np.logspace(0, np.log10(max_sqrt_n_pix), n_steps)
    sqrt_n_pix_list = np.unique(sqrt_n_pix_list.astype(int))
    results = []
    for sqrt_n_pix in tqdm(sqrt_n_pix_list):
        results.append(
            aperture_stats(
                data,
                mask,
                n_apertures=n_apertures,
                sqrt_n_pix=sqrt_n_pix,
                aperture_shape=aperture_shape,
                annular_thickness=annular_thickness,
                n_pix_tolerance=n_pix_tolerance,
            )
        )
    results = table.Table(results)
    results["expected_std_mean"] = results["std_mean"][0] / results["sqrt_n_pix"]
    results["expected_std_median"] = (
        np.sqrt(np.pi / 2) * results["std_median"][0] / results["sqrt_n_pix"]
    )
    return results

# %% ../../nbs/euclid/background.ipynb 7
def background_stats_plot(results, true_bkg_std=None, errorbars=False):
    fig, ax = plt.subplots()
    ax.plot(
        results["sqrt_n_pix"],
        results["expected_std_mean"],
        "--",
        label="expected std(mean)",
    )
    if errorbars:
        ax.errorbar(
            results["sqrt_n_pix"],
            results["std_mean"],
            results["err_std_mean"],
            fmt="-o",
            label="measured std(mean)",
        )
    else:
        ax.plot(
            results["sqrt_n_pix"], results["std_mean"], "-o", label="measured std(mean)"
        )
    ax.plot(
        results["sqrt_n_pix"],
        results["expected_std_median"],
        "--",
        label="expected std(median)",
    )
    if errorbars:
        ax.errorbar(
            results["sqrt_n_pix"],
            results["std_median"],
            results["err_std_mean"],
            fmt="-o",
            label="measured std(median)",
        )
    else:
        ax.plot(
            results["sqrt_n_pix"],
            results["std_median"],
            "-o",
            label="measured std(median)",
        )
    if true_bkg_std is not None:
        ax.axhline(true_bkg_std, ls=":", label="true bkg std")
    ax.set_yscale("log")
    ax.set_xscale("log")
    ax.yaxis.set_major_formatter(FuncFormatter(lambda y, _: f"{y:g}"))
    ax.xaxis.set_major_formatter(FuncFormatter(lambda y, _: f"{y:g}"))
    ax.xaxis.set_ticks(results["sqrt_n_pix"])
    ax.xaxis.set_minor_locator(NullLocator())
    ax.set_xlabel("sqrt(n_pix)")
    ax.set_ylabel("std(average)")
    ax.tick_params(axis="x", labelrotation=90)
    ax.legend()

# %% ../../nbs/euclid/background.ipynb 8
def measure(
    filename,  # the filename to test
    path,  # the folder containing the images
    create_mask=True,  # generate and apply a mask
    estimate_background=True,  # allow masking to estimate the background from the median of the image
    plots=True,  # output plots
    outpath=None,  # the folder where all output plots should be placed
    separate_detectors=True,  # consider multiple science extensions individually
    n_apertures=100,  # number of apertures per size
    max_sqrt_n_pix=100,  # maximum aperture size as sqrt(number of pixels)
    aperture_shape="square",  # square or circle
    annular_thickness=None,  # None for solid apertures, or a number on range (0, 1) to specify relative thickness of annulus
    n_pix_tolerance=0.1,  # the largest allowed relative deviation from the requested n_pix
    n_steps=20,  # the number of different sqrt_n_pix to measure
):
    """Determine statistics of the background."""
    path = os.path.abspath(os.path.expanduser(path))
    if outpath is not None:
        outpath = os.path.abspath(os.path.expanduser(outpath))
    else:
        outpath = os.path.join(path, "background_stats")
    results = {}
    fn = os.path.join(path, filename)
    with fits.open(fn, memmap=True) as hdul:
        sci_ext = [hdu.name for hdu in hdul if "SCI" in hdu.name]
        for ext in sci_ext:
            data = hdul[ext].data
            rms = hdul[ext.replace("SCI", "RMS")].data
            data[rms > 1e6] = np.nan
            if create_mask:
                mask, _ = fast_mask(data, estimate_background=estimate_background)
            else:
                mask = np.zeros(data.shape, dtype=bool)
            ext_results = stats_versus_size(
                data,
                mask,
                n_apertures=n_apertures,
                max_sqrt_n_pix=max_sqrt_n_pix,
                aperture_shape=aperture_shape,
                annular_thickness=annular_thickness,
                n_pix_tolerance=n_pix_tolerance,
            )
            background_stats_plot(ext_results)
            results[ext] = ext_results
    if not separate_detectors:
        results = table.vstack(results.values())
    elif len(results) == 1:
        results = list(results.values())[0]
    return results
