"""Calculate statistics to determine the surface brightness and spatial scale of the background variations"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/background_stats.ipynb.

# %% auto 0
__all__ = ['run']

# %% ../../nbs/euclid/background_stats.ipynb 2
def measure_stats(
    fn,  # filename of the image on which to measure statistics
):
    raise NotImplementedError

# %% ../../nbs/euclid/background_stats.ipynb 3
def run(
    obs_id,  # the observation_id to test
    path,  # the folder containing the images
    outpath=None,  # the folder where all output files should be placed
):
    """Determine statistics of the background"""
    path = os.path.abspath(os.path.expanduser(path))
    if outpath is not None:
        outpath = os.path.abspath(os.path.expanduser(outpath))
    else:
        outpath = os.path.join(path, "background_stats")
    raise NotImplementedError
