"""Estimate and subtract background in Euclid images."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/background.ipynb.

# %% auto 0
__all__ = ['get_background', 'make_background_plot']

# %% ../../nbs/euclid/background.ipynb 2
import matplotlib.pyplot as plt
import numpy as np
from photutils import Background2D, MedianBackground, SigmaClip

from ..main import configure_logging
from ..mask import plot_background

# %% ../../nbs/euclid/background.ipynb 4
plt.style.use("nicl.euclid.v1nicl")

# %% ../../nbs/euclid/background.ipynb 5
configure_logging(__name__)

# %% ../../nbs/euclid/background.ipynb 6
def get_background(image, mask=None, box_size=300, filter_size=3):
    bkg_estimator = MedianBackground() 
    sigma_clip = SigmaClip(sigma=3.0, maxiters=10)
    bkg = Background2D(image, box_size, mask=mask, filter_size=filter_size, exclude_percentile=90, bkg_estimator=bkg_estimator, sigma_clip=sigma_clip)
    return bkg

# %% ../../nbs/euclid/background.ipynb 7
def make_background_plot(image, bkg, mask=None, output_dir=None, label=None):
    image = np.where(mask, np.nan, image)
    plot_background(image, bkg, image - bkg.background, "Subtracted")
    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        plt.savefig(output_dir / f"{prefix}background.pdf")
        plt.close(fig)
