"""Euclid constants such as camera characteristics, swarp config templates."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/constants.ipynb.

# %% auto 0
__all__ = ['VIS', 'NISP', 'MER', 'SWARP_CONFIG_NISP', 'SWARP_CONFIG_VIS', 'SWARP_CONFIG_MER', 'Camera']

# %% ../../nbs/euclid/constants.ipynb 2
from dataclasses import dataclass
from typing import Tuple

import numpy as np

# %% ../../nbs/euclid/constants.ipynb 3
# camera constants


@dataclass(frozen=True)
class Camera:
    name: str
    chips: Tuple[str, ...]
    filters: Tuple[str, ...]
    pix_scale: float
    chip_subdivisions: Tuple[str, ...] = None
    readout_unit_size: Tuple[int, int] = None
    bad_pix_bits: Tuple[int, ...] = None
    n_dithers_per_obs: int = None
    chip_layout: np.ndarray = None  # 2D array of strings
    # chip_rotations is True if a half-turn rotation is required to align the orientations
    chip_rotations: np.ndarray = None  # 2D array of booleans, 
    nominal_zeropoint: float = None


    @property
    def extnames(self):
        if self.chip_subdivisions is None:
            return self.chips
        else:
            return tuple(
                f"{chip}.{sub}" for chip in self.chips for sub in self.chip_subdivisions
            )


VIS = Camera(
    name="VIS",
    chips=tuple(f"{x}-{y}" for x in range(1, 7) for y in range(1, 7)),
    chip_subdivisions=("E", "F", "G", "H"),
    readout_unit_size=(2066, 2048),
    filters=("I",),
    bad_pix_bits=(0,),  # 0 is the common flag for all invalid pixels
    pix_scale=0.1,
    n_dithers_per_obs=6,
    chip_layout=np.array(
        (("1-1.E", "1-1.F", "1-2.E", "1-2.F", "1-3.E", "1-3.F", "1-4.G", "1-4.H", "1-5.G", "1-5.H", "1-6.G", "1-6.H"),
         ("1-1.H", "1-1.G", "1-2.H", "1-2.G", "1-3.H", "1-3.G", "1-4.F", "1-4.E", "1-5.F", "1-5.E", "1-6.F", "1-6.E"),
         ("2-1.E", "2-1.F", "2-2.E", "2-2.F", "2-3.E", "2-3.F", "2-4.G", "2-4.H", "2-5.G", "2-5.H", "2-6.G", "2-6.H"),
         ("2-1.H", "2-1.G", "2-2.H", "2-2.G", "2-3.H", "2-3.G", "2-4.F", "2-4.E", "2-5.F", "2-5.E", "2-6.F", "2-6.E"),
         ("3-1.E", "3-1.F", "3-2.E", "3-2.F", "3-3.E", "3-3.F", "3-4.G", "3-4.H", "3-5.G", "3-5.H", "3-6.G", "3-6.H"),
         ("3-1.H", "3-1.G", "3-2.H", "3-2.G", "3-3.H", "3-3.G", "3-4.F", "3-4.E", "3-5.F", "3-5.E", "3-6.F", "3-6.E"),
         ("4-1.E", "4-1.F", "4-2.E", "4-2.F", "4-3.E", "4-3.F", "4-4.G", "4-4.H", "4-5.G", "4-5.H", "4-6.G", "4-6.H"),
         ("4-1.H", "4-1.G", "4-2.H", "4-2.G", "4-3.H", "4-3.G", "4-4.F", "4-4.E", "4-5.F", "4-5.E", "4-6.F", "4-6.E"),
         ("5-1.E", "5-1.F", "5-2.E", "5-2.F", "5-3.E", "5-3.F", "5-4.G", "5-4.H", "5-5.G", "5-5.H", "5-6.G", "5-6.H"),
         ("5-1.H", "5-1.G", "5-2.H", "5-2.G", "5-3.H", "5-3.G", "5-4.F", "5-4.E", "5-5.F", "5-5.E", "5-6.F", "5-6.E"),
         ("6-1.E", "6-1.F", "6-2.E", "6-2.F", "6-3.E", "6-3.F", "6-4.G", "6-4.H", "6-5.G", "6-5.H", "6-6.G", "6-6.H"),
         ("6-1.H", "6-1.G", "6-2.H", "6-2.G", "6-3.H", "6-3.G", "6-4.F", "6-4.E", "6-5.F", "6-5.E", "6-6.F", "6-6.E"))
    ),
    chip_rotations=np.zeros(dtype=bool, shape=(12, 12)),
    nominal_zeropoint=24.56605,
)
NISP = Camera(
    name="NISP",
    chips=tuple(f"DET{x}{y}" for x in range(1, 5) for y in range(1, 5)),
    readout_unit_size=(2040, 2040),
    filters=("Y", "J", "H"),
    bad_pix_bits=(0,),  # 0 is the common flag for all invalid pixels
    pix_scale=0.3,
    n_dithers_per_obs=4,
    chip_layout=np.array([[f"DET{y}{x}" for x in range(1, 5)] for y in range(1, 5)]),
    chip_rotations=np.array([[y > 2 for x in range(1, 5)] for y in range(1, 5)]),
    nominal_zeropoint=dict(H=29.94, J=30.03, Y=29.76),
)

MER = Camera(
    name="MER",
    chips=None,
    filters=("VIS", "NIR-Y", "NIR-J", "NIR-H"),
    bad_pix_bits=(0,),  # 0 is the common flag for all invalid pixels
    pix_scale=0.1,
)

# %% ../../nbs/euclid/constants.ipynb 4
# swarp config templates

SWARP_CONFIG_NISP = """
#----------------------------------- Output -----------------------------------
IMAGEOUT_NAME          coadd.fits      # Output filename
WEIGHTOUT_NAME         coadd.weight.fits # Output weight-map filename
 
HEADER_ONLY            N               # Only a header as an output file (Y/N)?
HEADER_SUFFIX          .head           # Filename extension for additional headers
 
#------------------------------- Input Weights --------------------------------

WEIGHT_TYPE            MAP_WEIGHT    # BACKGROUND,MAP_RMS,MAP_VARIANCE
                                       # or MAP_WEIGHT
RESCALE_WEIGHTS        N               # Rescale input weights/variances (Y/N)?
WEIGHT_SUFFIX          .weight.fits    # Suffix to use for weight-maps
WEIGHT_IMAGE                           # Weightmap filename if suffix not used
                                       # (all or for each weight-map)
WEIGHT_THRESH                          # Bad pixel weight-threshold
 
#------------------------------- Co-addition ----------------------------------
 
COMBINE                Y               # Combine resampled images (Y/N)?
COMBINE_TYPE           WEIGHTED         # MEDIAN,AVERAGE,MIN,MAX,WEIGHTED,CLIPPED
                                       # CHI-OLD,CHI-MODE,CHI-MEAN,SUM,
                                       # WEIGHTED_WEIGHT,MEDIAN_WEIGHT,
                                       # AND,NAND,OR or NOR
#CLIP_AMPFRAC           0.3             # Fraction of flux variation allowed
                                       # with clipping
#CLIP_SIGMA             4.0             # RMS error multiple variation allowed
                                       # with clipping
#CLIP_WRITELOG          N               # Write output file with coordinates of
                                       # clipped pixels (Y/N)
#CLIP_LOGNAME           clipped.log     # Name of output file with coordinates
                                       # of clipped pixels
#BLANK_BADPIXELS        N               # Set to 0 pixels having a weight of 0
 
#-------------------------------- Astrometry ----------------------------------
 
CELESTIAL_TYPE         NATIVE          # NATIVE, PIXEL, EQUATORIAL,
                                       # GALACTIC,ECLIPTIC, or SUPERGALACTIC
PROJECTION_TYPE        TAN             # Any WCS projection code or NONE
PROJECTION_ERR         0.001           # Maximum projection error (in output
                                       # pixels), or 0 for no approximation
CENTER_TYPE            ALL             # MANUAL, ALL or MOST
CENTER         00:00:00.0, +00:00:00.0 # Coordinates of the image center
PIXELSCALE_TYPE        MANUAL          # MANUAL,FIT,MIN,MAX or MEDIAN
PIXEL_SCALE            0.3             # Pixel scale
IMAGE_SIZE             0               # Image size (0 = AUTOMATIC)
 
#-------------------------------- Resampling ----------------------------------
 
RESAMPLE               Y               # Resample input images (Y/N)?
RESAMPLE_DIR           .               # Directory path for resampled images
RESAMPLE_SUFFIX        .resamp.fits    # filename extension for resampled images
 
RESAMPLING_TYPE        LANCZOS2        # NEAREST,BILINEAR,LANCZOS2,LANCZOS3
                                       # LANCZOS4 (1 per axis) or FLAGS
OVERSAMPLING           0               # Oversampling in each dimension
                                       # (0 = automatic)
INTERPOLATE            N               # Interpolate bad input pixels (Y/N)?
                                       # (all or for each image)
 
FSCALASTRO_TYPE        VARIABLE            # NONE,FIXED, or VARIABLE
FSCALE_KEYWORD         PHOSCALE            # FITS keyword for the multiplicative
                                       # factor applied to each input image
FSCALE_DEFAULT         1.0             # Default FSCALE value if not in header
 
GAIN_KEYWORD           GAIN            # FITS keyword for effect. gain (e-/ADU)
GAIN_DEFAULT           0.0             # Default gain if no FITS keyword found

SATLEV_KEYWORD         SATURATE        # FITS keyword for saturation level (ADU)
SATLEV_DEFAULT         50000.0         # Default saturation if no FITS keyword

#--------------------------- Background subtraction ---------------------------
 
SUBTRACT_BACK          N               # Subtraction sky background (Y/N)?
                                       # (all or for each image)
 
BACK_TYPE              AUTO            # AUTO or MANUAL
                                       # (all or for each ima  ge)
BACK_DEFAULT           0.0             # Default background value in MANUAL
                                       # (all or for each image)
BACK_SIZE              32             # Background mesh size (pixels)
                                       # (all or for each image)
BACK_FILTERSIZE        5               # Background map filter range (meshes)
                                       # (all or for each image)
 
#------------------------------ Memory management -----------------------------
 
VMEM_DIR               .               # Directory path for swap files
VMEM_MAX               6144            # Maximum amount of virtual memory (MB)
MEM_MAX                6144            # Maximum amount of usable RAM (MB)
COMBINE_BUFSIZE        6144            # RAM dedicated to co-addition(MB)
 
#------------------------------ Miscellaneous ---------------------------------
 
DELETE_TMPFILES        Y               # Delete temporary resampled FITS files
                                       # (Y/N)?
COPY_KEYWORDS          ZPAB, ZPABE, ZPVEGA, ZPVEGAE # List of FITS keywords to propagate
                                       # from the input to the output headers
WRITE_FILEINFO         N               # Write information about each input
                                       # file in the output image header?
WRITE_XML              Y               # Write XML file (Y/N)?
XML_NAME               swarp.xml       # Filename for XML output
VERBOSE_TYPE           NORMAL          # QUIET,LOG,NORMAL, or FULL
 
NTHREADS               0               # Number of simultaneous threads for
                                       # the SMP version of SWarp
                                       # 0 = automatic
"""

# %% ../../nbs/euclid/constants.ipynb 5
SWARP_CONFIG_VIS = """
#----------------------------------- Output -----------------------------------
IMAGEOUT_NAME          coadd.fits      # Output filename
WEIGHTOUT_NAME         coadd.weight.fits # Output weight-map filename
 
HEADER_ONLY            N               # Only a header as an output file (Y/N)?
HEADER_SUFFIX          .head           # Filename extension for additional headers
 
#------------------------------- Input Weights --------------------------------

WEIGHT_TYPE            MAP_WEIGHT    # BACKGROUND,MAP_RMS,MAP_VARIANCE
                                       # or MAP_WEIGHT
RESCALE_WEIGHTS        N               # Rescale input weights/variances (Y/N)?
WEIGHT_SUFFIX          .weight.fits    # Suffix to use for weight-maps
WEIGHT_IMAGE                           # Weightmap filename if suffix not used
                                       # (all or for each weight-map)
WEIGHT_THRESH                          # Bad pixel weight-threshold
 
#------------------------------- Co-addition ----------------------------------
 
COMBINE                Y               # Combine resampled images (Y/N)?
COMBINE_TYPE           WEIGHTED         # MEDIAN,AVERAGE,MIN,MAX,WEIGHTED,CLIPPED
                                       # CHI-OLD,CHI-MODE,CHI-MEAN,SUM,
                                       # WEIGHTED_WEIGHT,MEDIAN_WEIGHT,
                                       # AND,NAND,OR or NOR
#CLIP_AMPFRAC           0.3             # Fraction of flux variation allowed
                                       # with clipping
#CLIP_SIGMA             4.0             # RMS error multiple variation allowed
                                       # with clipping
#CLIP_WRITELOG          N               # Write output file with coordinates of
                                       # clipped pixels (Y/N)
#CLIP_LOGNAME           clipped.log     # Name of output file with coordinates
                                       # of clipped pixels
#BLANK_BADPIXELS        N               # Set to 0 pixels having a weight of 0
 
#-------------------------------- Astrometry ----------------------------------
 
CELESTIAL_TYPE         NATIVE          # NATIVE, PIXEL, EQUATORIAL,
                                       # GALACTIC,ECLIPTIC, or SUPERGALACTIC
PROJECTION_TYPE        TAN             # Any WCS projection code or NONE
PROJECTION_ERR         0.001           # Maximum projection error (in output
                                       # pixels), or 0 for no approximation
CENTER_TYPE            ALL             # MANUAL, ALL or MOST
CENTER         00:00:00.0, +00:00:00.0 # Coordinates of the image center
PIXELSCALE_TYPE        MANUAL          # MANUAL,FIT,MIN,MAX or MEDIAN
PIXEL_SCALE            0.1             # Pixel scale
IMAGE_SIZE             0               # Image size (0 = AUTOMATIC)
 
#-------------------------------- Resampling ----------------------------------
 
RESAMPLE               Y               # Resample input images (Y/N)?
RESAMPLE_DIR           .               # Directory path for resampled images
RESAMPLE_SUFFIX        .resamp.fits    # filename extension for resampled images
 
RESAMPLING_TYPE        LANCZOS2        # NEAREST,BILINEAR,LANCZOS2,LANCZOS3
                                       # LANCZOS4 (1 per axis) or FLAGS
OVERSAMPLING           0               # Oversampling in each dimension
                                       # (0 = automatic)
INTERPOLATE            N               # Interpolate bad input pixels (Y/N)?
                                       # (all or for each image)
 
FSCALASTRO_TYPE        VARIABLE            # NONE,FIXED, or VARIABLE
FSCALE_KEYWORD         FLXSCALE            # FITS keyword for the multiplicative
                                       # factor applied to each input image
FSCALE_DEFAULT         1.0             # Default FSCALE value if not in header
 
GAIN_KEYWORD           GAIN            # FITS keyword for effect. gain (e-/ADU)
GAIN_DEFAULT           0.0             # Default gain if no FITS keyword found

SATLEV_KEYWORD         SATURATE        # FITS keyword for saturation level (ADU)
SATLEV_DEFAULT         50000.0         # Default saturation if no FITS keyword

#--------------------------- Background subtraction ---------------------------
 
SUBTRACT_BACK          N               # Subtraction sky background (Y/N)?
                                       # (all or for each image)
 
BACK_TYPE              AUTO            # AUTO or MANUAL
                                       # (all or for each ima  ge)
BACK_DEFAULT           0.0             # Default background value in MANUAL
                                       # (all or for each image)
BACK_SIZE              32             # Background mesh size (pixels)
                                       # (all or for each image)
BACK_FILTERSIZE        5               # Background map filter range (meshes)
                                       # (all or for each image)
 
#------------------------------ Memory management -----------------------------
 
VMEM_DIR               .               # Directory path for swap files
VMEM_MAX               6144            # Maximum amount of virtual memory (MB)
MEM_MAX                6144            # Maximum amount of usable RAM (MB)
COMBINE_BUFSIZE        6144            # RAM dedicated to co-addition(MB)
 
#------------------------------ Miscellaneous ---------------------------------
 
DELETE_TMPFILES        Y               # Delete temporary resampled FITS files
                                       # (Y/N)?
COPY_KEYWORDS          ZPAB, ZPABE, ZPVEGA, ZPVEGAE # List of FITS keywords to propagate
                                       # from the input to the output headers
WRITE_FILEINFO         N               # Write information about each input
                                       # file in the output image header?
WRITE_XML              Y               # Write XML file (Y/N)?
XML_NAME               swarp.xml       # Filename for XML output
VERBOSE_TYPE           NORMAL          # QUIET,LOG,NORMAL, or FULL
 
NTHREADS               0               # Number of simultaneous threads for
                                       # the SMP version of SWarp
                                       # 0 = automatic
"""

# %% ../../nbs/euclid/constants.ipynb 6
SWARP_CONFIG_MER = """
#----------------------------------- Output -----------------------------------
IMAGEOUT_NAME          coadd.fits      # Output filename
WEIGHTOUT_NAME         coadd.weight.fits # Output weight-map filename
 
HEADER_ONLY            N               # Only a header as an output file (Y/N)?
HEADER_SUFFIX          .head           # Filename extension for additional headers
 
#------------------------------- Input Weights --------------------------------

#WEIGHT_TYPE            MAP_WEIGHT    # BACKGROUND,MAP_RMS,MAP_VARIANCE
                                       # or MAP_WEIGHT
RESCALE_WEIGHTS        N               # Rescale input weights/variances (Y/N)?
#WEIGHT_SUFFIX          .weight.fits    # Suffix to use for weight-maps
WEIGHT_IMAGE                           # Weightmap filename if suffix not used
                                       # (all or for each weight-map)
WEIGHT_THRESH                          # Bad pixel weight-threshold
 
#------------------------------- Co-addition ----------------------------------
 
COMBINE                Y               # Combine resampled images (Y/N)?
COMBINE_TYPE           AVERAGE         # MEDIAN,AVERAGE,MIN,MAX,WEIGHTED,CLIPPED
                                       # CHI-OLD,CHI-MODE,CHI-MEAN,SUM,
                                       # WEIGHTED_WEIGHT,MEDIAN_WEIGHT,
                                       # AND,NAND,OR or NOR
#CLIP_AMPFRAC           0.3             # Fraction of flux variation allowed
                                       # with clipping
#CLIP_SIGMA             4.0             # RMS error multiple variation allowed
                                       # with clipping
#CLIP_WRITELOG          N               # Write output file with coordinates of
                                       # clipped pixels (Y/N)
#CLIP_LOGNAME           clipped.log     # Name of output file with coordinates
                                       # of clipped pixels
#BLANK_BADPIXELS        N               # Set to 0 pixels having a weight of 0
 
#-------------------------------- Astrometry ----------------------------------
 
CELESTIAL_TYPE         NATIVE          # NATIVE, PIXEL, EQUATORIAL,
                                       # GALACTIC,ECLIPTIC, or SUPERGALACTIC
PROJECTION_TYPE        TAN             # Any WCS projection code or NONE
PROJECTION_ERR         0.001           # Maximum projection error (in output
                                       # pixels), or 0 for no approximation
CENTER_TYPE            ALL             # MANUAL, ALL or MOST
CENTER         00:00:00.0, +00:00:00.0 # Coordinates of the image center
PIXELSCALE_TYPE        MANUAL          # MANUAL,FIT,MIN,MAX or MEDIAN
PIXEL_SCALE            0.1             # Pixel scale
IMAGE_SIZE             0               # Image size (0 = AUTOMATIC)
 
#-------------------------------- Resampling ----------------------------------
 
RESAMPLE               Y               # Resample input images (Y/N)?
RESAMPLE_DIR           .               # Directory path for resampled images
RESAMPLE_SUFFIX        .resamp.fits    # filename extension for resampled images
 
RESAMPLING_TYPE        BILINEAR        # NEAREST,BILINEAR,LANCZOS2,LANCZOS3
                                       # LANCZOS4 (1 per axis) or FLAGS
OVERSAMPLING           0               # Oversampling in each dimension
                                       # (0 = automatic)
INTERPOLATE            N               # Interpolate bad input pixels (Y/N)?
                                       # (all or for each image)
 
FSCALASTRO_TYPE        VARIABLE            # NONE,FIXED, or VARIABLE
FSCALE_KEYWORD         FLXSCALE            # FITS keyword for the multiplicative
                                       # factor applied to each input image
FSCALE_DEFAULT         1.0             # Default FSCALE value if not in header
 
GAIN_KEYWORD           GAIN            # FITS keyword for effect. gain (e-/ADU)
GAIN_DEFAULT           0.0             # Default gain if no FITS keyword found

SATLEV_KEYWORD         SATURATE        # FITS keyword for saturation level (ADU)
SATLEV_DEFAULT         50000.0         # Default saturation if no FITS keyword

#--------------------------- Background subtraction ---------------------------
 
SUBTRACT_BACK          N               # Subtraction sky background (Y/N)?
                                       # (all or for each image)
 
BACK_TYPE              AUTO            # AUTO or MANUAL
                                       # (all or for each ima  ge)
BACK_DEFAULT           0.0             # Default background value in MANUAL
                                       # (all or for each image)
BACK_SIZE              32             # Background mesh size (pixels)
                                       # (all or for each image)
BACK_FILTERSIZE        5               # Background map filter range (meshes)
                                       # (all or for each image)
 
#------------------------------ Memory management -----------------------------
 
VMEM_DIR               .               # Directory path for swap files
VMEM_MAX               6144            # Maximum amount of virtual memory (MB)
MEM_MAX                6144            # Maximum amount of usable RAM (MB)
COMBINE_BUFSIZE        6144            # RAM dedicated to co-addition(MB)
 
#------------------------------ Miscellaneous ---------------------------------
 
DELETE_TMPFILES        Y               # Delete temporary resampled FITS files
                                       # (Y/N)?
COPY_KEYWORDS          FILTER, MAGZERO # List of FITS keywords to propagate
                                       # from the input to the output headers
WRITE_FILEINFO         N               # Write information about each input
                                       # file in the output image header?
WRITE_XML              Y               # Write XML file (Y/N)?
XML_NAME               swarp.xml       # Filename for XML output
VERBOSE_TYPE           NORMAL          # QUIET,LOG,NORMAL, or FULL
 
NTHREADS               0               # Number of simultaneous threads for
                                       # the SMP version of SWarp
                                       # 0 = automatic
"""
