"""Perform background matching to correct for discontinuities between detectors."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/continuity.ipynb.

# %% auto 0
__all__ = ['do_resamp_images_overlap', 'bkg_match', 'slice_to_coords', 'can_wcs_shift_by_int', 'get_overlap_slices',
           'get_overlap_chip', 'compute_offset_between_chips', 'polygon_photometry', 'form_dither_pairs',
           'measure_offset_per_dither_pair', 'measure_offset_per_observation', 'solve_for_correction_per_observation',
           'apply_correction', 'correct_dither']

# %% ../../nbs/euclid/continuity.ipynb 2
import logging
import multiprocessing as mp
from functools import partial
from pathlib import Path

import numpy as np
from astropy.coordinates import SkyCoord
from astropy.io import fits
from astropy.wcs import WCS
from numpy.linalg import lstsq
from regions import PolygonSkyRegion
from spherical_geometry.polygon import SphericalPolygon

from nicl.euclid.utilities import (
    get_dither_id_from_filename,
    get_obs_id_from_filename,
)
from nicl.mask import fast_mask
from nicl.utilities import does_image_overlap_with_skyregion, sigma_clip_stats

# %% ../../nbs/euclid/continuity.ipynb 4
def do_resamp_images_overlap(path1, path2, threshold=0.01):
    """Check if two resampled images overlap."""
    logger = logging.getLogger(__name__)
    # find the original images before resampling
    path1_orig = (
        path1.with_suffix("").with_suffix("").with_suffix("").with_suffix(path1.suffix)
    )
    path2_orig = (
        path2.with_suffix("").with_suffix("").with_suffix("").with_suffix(path2.suffix)
    )
    # check if they both exist
    if not path1_orig.exists() or not path2_orig.exists():
        raise FileNotFoundError(
            f"One of the original images does not exist: {path1_orig}, {path2_orig}"
        )
    logger.debug(f"Checking overlap between {path1_orig} and {path2_orig}")
    # create sky regions from the headers
    hdr1 = fits.getheader(path1_orig, 1)
    hdr2 = fits.getheader(path2_orig, 1)
    sky_reg1 = SphericalPolygon.from_wcs(hdr1)
    sky_reg2 = SphericalPolygon.from_wcs(hdr2)
    # check if they overlap
    if not sky_reg1.intersects_poly(sky_reg2):
        return False
    overlap = sky_reg1.intersection(sky_reg2)
    area_overlap = overlap.area()
    area1 = sky_reg1.area()
    area2 = sky_reg2.area()
    frac1 = area_overlap / area2
    frac2 = area_overlap / area1
    logger.debug(
        f"Overlap area: {area_overlap}, area1: {area1}, area2: {area2}, frac1: {frac1}, frac2: {frac2}"
    )
    return frac1 > threshold or frac2 > threshold


def bkg_match(
    paths,
    corr_order=0,
):
    logger = logging.getLogger(__name__)
    paths.sort()
    ids = []
    for path in paths:
        obs_id = get_obs_id_from_filename(path.name)
        dither_id = get_dither_id_from_filename(path.name)
        ids.append((obs_id, dither_id))
    a = []
    b = []
    solution_map = []
    match corr_order:
        case 0:
            n_unknowns_per_img = 1
        case 1:
            n_unknowns_per_img = 3
        case 2:
            n_unknowns_per_img = 5
    for i, path in enumerate(paths[:-1]):
        obs_id, dither_id = ids[i]
        # find out all images that belong to the other exposures and overlap with the current one
        other_paths = []
        for j, other_path in enumerate(paths[i + 1 :]):
            other_obs_id, other_dither_id = ids[i + j + 1]
            if other_obs_id != obs_id and other_dither_id != dither_id:
                if do_resamp_images_overlap(path, other_path):
                    other_paths.append(other_path)
        logger.debug(
            f"Found {len(other_paths)} overlapping images for {path.name}: {[other.name for other in other_paths]}"
        )
        if other_paths:
            with (
                fits.open(path, mode="update") as hdul,
                fits.open(
                    path.with_suffix(".weight.fits"), mode="update"
                ) as hdul_weight,
            ):
                # apply flux scaling
                sci_hdr = hdul[0].header
                flxscale = sci_hdr.get("FLXSCALE", 1.0)
                hdul[0].data = hdul[0].data * flxscale
                hdul[0].header["FLXSCALE"] = 1.0
                hdul_weight[0].data = hdul_weight[0].data / flxscale**2
                hdul_weight[0].header["FLXSCALE"] = 1.0
                hdul.flush()
                hdul_weight.flush()
                for other_path in other_paths:
                    logger.debug(f"Comparing {path.name} to {other_path.name}...")
                    with (
                        fits.open(other_path, mode="update") as other_hdul,
                        fits.open(
                            other_path.with_suffix(".weight.fits"), mode="update"
                        ) as other_hdul_weight,
                    ):
                        # apply flux scaling
                        other_sci_hdr = other_hdul[0].header
                        other_flxscale = other_sci_hdr.get("FLXSCALE", 1.0)
                        other_hdul[0].data = other_hdul[0].data * other_flxscale
                        other_hdul[0].header["FLXSCALE"] = 1.0
                        other_hdul_weight[0].data = (
                            other_hdul_weight[0].data / other_flxscale**2
                        )
                        other_hdul_weight[0].header["FLXSCALE"] = 1.0
                        other_hdul.flush()
                        other_hdul_weight.flush()
                        slice1, slice2 = get_overlap_slices(sci_hdr, other_sci_hdr)
                        diff_img = hdul[0].data[slice1] - other_hdul[0].data[slice2]
                        diff_img_rms = np.sqrt(
                            1 / hdul_weight[0].data[slice1]
                            + 1 / other_hdul_weight[0].data[slice2]
                        )
                        idx_valid = np.isfinite(diff_img_rms)
                        n_eqs = np.sum(idx_valid)
                        idx = paths.index(path)
                        idx_other = paths.index(other_path)
                        if idx in solution_map:
                            idx_solution = solution_map.index(idx)
                        else:
                            solution_map.append(idx)
                            idx_solution = len(solution_map) - 1
                        if idx_other in solution_map:
                            idx_other_solution = solution_map.index(idx_other)
                        else:
                            solution_map.append(idx_other)
                            idx_other_solution = len(solution_map) - 1
                        match corr_order:
                            case 0:
                                coeff_array = np.zeros(
                                    (n_eqs, n_unknowns_per_img * len(solution_map))
                                )
                                coeff_array[:, idx_solution] = 1
                                coeff_array[:, idx_other_solution] = -1
                                offset = -diff_img[idx_valid].ravel()
                                rms = diff_img_rms[idx_valid].ravel()
                                coeff_array = coeff_array / rms[:, np.newaxis]
                                offset = offset / rms
                            case 1:
                                coords1 = slice_to_coords(slice1)
                                coords2 = slice_to_coords(slice2)
                                coeff_array = np.zeros(
                                    (n_eqs, n_unknowns_per_img * len(solution_map))
                                )
                                coeff_array[:, idx_solution * n_unknowns_per_img] = 1
                                coeff_array[
                                    :, idx_solution * n_unknowns_per_img + 1
                                ] = coords1[:, 0]
                                coeff_array[
                                    :, idx_solution * n_unknowns_per_img + 2
                                ] = coords1[:, 1]
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img
                                ] = -1
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img + 1
                                ] = -coords2[:, 0]
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img + 2
                                ] = -coords2[:, 1]
                                offset = -diff_img[idx_valid].ravel()
                                rms = diff_img_rms[idx_valid].ravel()
                                coeff_array = coeff_array / rms[:, np.newaxis]
                                offset = offset / rms
                            case 2:
                                coords1 = slice_to_coords(slice1)
                                coords2 = slice_to_coords(slice2)
                                coeff_array = np.zeros(
                                    (n_eqs, n_unknowns_per_img * len(solution_map))
                                )
                                coeff_array[:, idx_solution * n_unknowns_per_img] = 1
                                coeff_array[
                                    :, idx_solution * n_unknowns_per_img + 1
                                ] = coords1[:, 0]
                                coeff_array[
                                    :, idx_solution * n_unknowns_per_img + 2
                                ] = coords1[:, 1]
                                coeff_array[
                                    :, idx_solution * n_unknowns_per_img + 3
                                ] = coords1[:, 0] ** 2
                                coeff_array[
                                    :, idx_solution * n_unknowns_per_img + 4
                                ] = coords1[:, 1] ** 2
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img
                                ] = -1
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img + 1
                                ] = -coords2[:, 0]
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img + 2
                                ] = -coords2[:, 1]
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img + 3
                                ] = -(coords2[:, 0] ** 2)
                                coeff_array[
                                    :, idx_other_solution * n_unknowns_per_img + 4
                                ] = -(coords2[:, 1] ** 2)
                                offset = -diff_img[idx_valid].ravel()
                                rms = diff_img_rms[idx_valid].ravel()
                                coeff_array = coeff_array / rms[:, np.newaxis]
                                offset = offset / rms
                        a.append(coeff_array)
                        b.append(offset)
    # padd zeros to coeff_array to match the longest one
    max_len = max([coeff.shape[1] for coeff in a])
    for i in range(len(a)):
        coeff = a[i]
        if coeff.shape[1] < max_len:
            coeff = np.pad(
                coeff, ((0, 0), (0, max_len - coeff.shape[1])), mode="constant"
            )
            a[i] = coeff
    # stack all coeff_array
    coeff_array = np.vstack(a)
    # stack all offset
    offset = np.hstack(b)
    # solve the system of equations
    num_solutions = a.shape[1]
    logger.debug(f"number of equations: {len(a)}")
    logger.debug(f"number of unknowns: {num_solutions}")
    solutions, residuals, rank, _ = lstsq(a, b, rcond=None)
    if rank < num_solutions or len(a) < num_solutions:
        residuals = np.linalg.norm(b - a @ solutions) / np.sqrt(len(b))
    logger.debug(f"rank: {rank}, residuals: {residuals}")
    # apply the solutions to the images
    for i, path in enumerate(paths):
        idx_sol = solution_map.index(i)
        solution = solutions[idx_sol : idx_sol + n_unknowns_per_img]
        with fits.open(path, mode="update") as hdul:
            if corr_order == 0:
                hdul[0].data = hdul[0].data + solution[0]
            elif corr_order == 1:
                # Apply a first-order polynomial correction to the image data
                # solution = [offset, coeff_x, coeff_y]
                ny, nx = hdul[0].data.shape
                y, x = np.indices((ny, nx))
                correction = solution[0] + solution[1] * x + solution[2] * y
                hdul[0].data = hdul[0].data + correction
            elif corr_order == 2:
                # Apply a second-order polynomial correction to the image data
                # solution = [offset, coeff_x, coeff_y, coeff_x2, coeff_y2]
                ny, nx = hdul[0].data.shape
                y, x = np.indices((ny, nx))
                correction = (
                    solution[0]
                    + solution[1] * x
                    + solution[2] * y
                    + solution[3] * x**2
                    + solution[4] * y**2
                )
                hdul[0].data = hdul[0].data + correction
            else:
                raise ValueError(f"Unknown correction order: {corr_order}")
            hdul.flush()

# %% ../../nbs/euclid/continuity.ipynb 5
def slice_to_coords(idx):
    """Given a tuple of two slice objects (as returned by numpy.index_exp), return an array of (x, y) index pairs.

    Parameters
    ----------
    idx : tuple of slice
        Tuple of two slice objects, typically (slice(y0, y1, step_y), slice(x0, x1, step_x)),
        representing the region of an image.

    Returns
    -------
    coords : ndarray of shape (N, 2)
        Array of (x, y) pixel coordinate pairs covering the region defined by the slices,
        where N is the total number of pixels in the region.

    Notes
    -----
    The output is a 2D array where each row is (x, y) for a pixel in the region.
    The order is row-major (y varies slowest).

    """
    ys, xs = idx  # unpack the two slices
    y0, y1, sy = ys.start or 0, ys.stop, ys.step or 1
    x0, x1, sx = xs.start or 0, xs.stop, xs.step or 1

    row_range = np.arange(y0, y1, sy)
    col_range = np.arange(x0, x1, sx)

    XX, YY = np.meshgrid(col_range, row_range)
    # stack into (rows, cols, 2) of (x, y)
    coords = np.stack((XX.ravel(), YY.ravel()), axis=-1)
    return coords


def can_wcs_shift_by_int(wcs1, wcs2):
    """Check if wcs1 and wcs2 are integer shiftable to match each other."""
    # 1) Must have the same number of axes
    if wcs1.wcs.naxis != wcs2.wcs.naxis:
        return False

    # 2) Match the reference world coord
    if not np.array_equal(wcs1.wcs.crval, wcs2.wcs.crval):
        return False

    # 3) Match the projection types & units
    if tuple(wcs1.wcs.ctype) != tuple(wcs2.wcs.ctype):
        return False
    if tuple(wcs1.wcs.cunit) != tuple(wcs2.wcs.cunit):
        return False

    # 4) Match the rotation+scale matrix (PC or CD)
    if hasattr(wcs1.wcs, "pc") and hasattr(wcs2.wcs, "pc"):
        if not np.array_equal(wcs1.wcs.pc, wcs2.wcs.pc):
            return False
        # If you’re using PC, you should also compare CDELT
        if not np.array_equal(wcs1.wcs.cdelt, wcs2.wcs.cdelt):
            return False
    else:
        # fallback to comparing CD (if present)
        if not np.array_equal(wcs1.wcs.cd, wcs2.wcs.cd):
            return False
    # 5) Check if the CRPIX offset is an integer
    crpix_offset = wcs1.wcs.crpix - wcs2.wcs.crpix
    for crpix in crpix_offset:
        if not crpix.is_integer():
            return False
    return True


def get_overlap_slices(hdr1, hdr2):
    """Return slice indices for the overlapping region of two images.

    Parameters
    ----------
    hdr1 : astropy.io.fits.Header
        The header of the first image
    hdr2 : astropy.io.fits.Header
        The header of the second image

    Returns
    -------
    tuple or None
        If the images can be aligned by an integer pixel shift and have an overlapping region,
        returns a tuple of two slice objects (numpy.index_exp):
        - The first slice extracts the overlapping region from the first image
        - The second slice extracts the corresponding region from the second image
        If the images cannot be integer-shifted or don't overlap, returns None

    """
    # extract CRPIX offsets
    w1, w2 = WCS(hdr1), WCS(hdr2)
    if not can_wcs_shift_by_int(w1, w2):
        return None
    cr1, cr2 = w1.wcs.crpix, w2.wcs.crpix
    dx, dy = int(cr2[0] - cr1[0]), int(cr2[1] - cr1[1])
    # image dimensions
    ny1, nx1 = hdr1["NAXIS2"], hdr1["NAXIS1"]
    ny2, nx2 = hdr2["NAXIS2"], hdr2["NAXIS1"]
    # in data1 frame data2 is shifted by (-dx, -dy)
    y0_1 = max(0, -dy)
    x0_1 = max(0, -dx)
    y1_1 = min(ny1, ny2 - dy)
    x1_1 = min(nx1, nx2 - dx)
    # check if any overlap at all
    if y0_1 >= y1_1 or x0_1 >= x1_1:
        return None
    # corresponding region in data2:
    y0_2 = y0_1 + dy
    x0_2 = x0_1 + dx
    y1_2 = y1_1 + dy
    x1_2 = x1_1 + dx
    return np.index_exp[y0_1:y1_1, x0_1:x1_1], np.index_exp[y0_2:y1_2, x0_2:x1_2]

# %% ../../nbs/euclid/continuity.ipynb 6
def get_overlap_chip(hdr, hdul, chip_layout, threshold=0.01):
    """Get the chip id (target dither) that overlaps with the chip pair in the current dither. Sparsely sampling image boundary for better speed."""
    sky_reg = SphericalPolygon.from_wcs(hdr)
    chips = []
    for chip in np.nditer(chip_layout):
        chip = str(chip)
        hdr = hdul[chip + ".SCI"].header
        is_overlapped = does_image_overlap_with_skyregion(
            hdr, sky_reg, threshold=threshold
        )
        if is_overlapped:
            chips.append(chip)
    return chips


def compute_offset_between_chips(hdu, target_hdus, steps=10):
    """Compute the offsets between the overlapping chips in the target dither and the given chip in the current dither."""
    # use SphericalPolygon to compute the accurate overlap region
    current_poly = SphericalPolygon.from_wcs(hdu.header, steps=steps)
    offsets = []
    for target_hdu in target_hdus:
        target_poly = SphericalPolygon.from_wcs(target_hdu.header, steps=steps)
        if not current_poly.intersects_poly(target_poly):
            raise ValueError(
                f"Chip {target_hdu.header['extname']} does not overlap with the current dither chip {hdu.header['extname']}."
            )
        overlap_poly = current_poly.intersection(target_poly)
        sb, sb_err = polygon_photometry(overlap_poly, hdu)
        target_sb, target_sb_err = polygon_photometry(overlap_poly, target_hdu)
        # compute the offset
        offset = sb - target_sb
        offset_err = np.sqrt(sb_err**2 + target_sb_err**2)
        offsets.append((offset, offset_err))
    return offsets


def polygon_photometry(skyreg, hdu):
    """Perform polygon photometry on the given data using the provided sky region and WCS.

    This function computes the mean value of the pixels within the polygon region.
    """
    img = hdu.data
    hdr = hdu.header
    sky_area = skyreg.area()
    # get magnitude zero point; MAGZEROP is for VIS, ZPAB is the default key for NISP
    if "QUADID" in hdr:
        target_mag_zpt = 24.56605
        target_pix_scl = 0.1
        mag_zpt = float(hdr.get("MAGZEROP"))
    else:
        target_mag_zpt = 30
        target_pix_scl = 0.3
        mag_zpt = hdr.get("ZPAB")
    if mag_zpt is None:
        raise ValueError(
            "Magnitude zero point not found in header (missing MAGZEROP and ZPAB keys)"
        )
    # construct a PolygonSkyRegion to do photometry
    ra, dec = list(skyreg.to_radec())[0]
    skyreg_ = PolygonSkyRegion(SkyCoord(ra[:-1], dec[:-1], unit="deg"))
    # Convert the sky region to pixel coordinates
    wcs = WCS(hdr)
    pixreg = skyreg_.to_pixel(wcs)
    # mode="exact" not implemented in regions yet for polygons
    # also we don't need accurate pixel footprint since we are taking the mean/median
    regmask = pixreg.to_mask(mode="center")
    nanmask = np.isnan(img)
    extracted_data = regmask.get_values(img, mask=nanmask)
    # print(extracted_data)
    robust_mean, _, _, robust_mean_err = sigma_clip_stats(
        extracted_data, sigma_upper=2.5, sigma_lower=3, ngood_min=3
    )
    # print(f"robust mean: {robust_mean}, robust mean error: {robust_mean_err}")
    if not np.isnan(robust_mean):
        pix_area = pixreg.area
        # convert sky area from steradians to square arcseconds
        sky_area = sky_area * (180 * 3600 / np.pi) ** 2
        sky_area_per_pix = sky_area / pix_area
        # sky_area_per_pix=wcs.proj_plane_pixel_area().to(u.arcsec**2).value
        # print(f"sky area per pixel: {sky_area_per_pix}")
        # generalize to the same zpt and pixel scale
        adjusted_intensity = (
            robust_mean
            / sky_area_per_pix
            * target_pix_scl**2
            * 10 ** (-0.4 * (mag_zpt - target_mag_zpt))
        )
        adjusted_intensity_error = (
            robust_mean_err
            / sky_area_per_pix
            * target_pix_scl**2
            * 10 ** (-0.4 * (mag_zpt - target_mag_zpt))
        )
        # adjusted_intensity = robust_mean / sky_area_per_pix * target_pix_scl**2
        # adjusted_intensity_error = robust_mean_err / sky_area_per_pix * target_pix_scl**2
        # adjusted_intensity = robust_mean
        # adjusted_intensity_error = robust_mean_err
        return adjusted_intensity, adjusted_intensity_error
    else:
        return np.nan, np.nan


def form_dither_pairs(dithers):
    """Form dither pairs from the list of dither files. It removes short exposures for now."""
    dithers.sort()
    dithers_ = []
    for dither in dithers:
        dither_id = get_dither_id_from_filename(dither)
        if len(dither_id) > 1 and dither_id.endswith("2"):
            continue
        dithers_.append(dither)
    # form unique dither pairs among four dithers
    dither_pairs = []
    for i in range(len(dithers_)):
        for j in range(i + 1, len(dithers_)):
            dither_pairs.append((dithers_[i], dithers_[j]))
    return dither_pairs


def _mask_in_place(hdu, mask):
    """Mask the data in place. So we don't need to pass around the dq hdu."""
    if mask is None:
        return
    if hdu.data is None:
        raise ValueError("Data is None")
    if mask.shape != hdu.data.shape:
        raise ValueError("Mask shape does not match data shape")
    # mask the data in place
    hdu.data[mask] = np.nan

# %% ../../nbs/euclid/continuity.ipynb 7
def measure_offset_per_dither_pair(dither_pair, instrument):
    dither1, dither2 = dither_pair
    chip_pairs = []
    offsets = []
    with fits.open(dither1) as hdul1, fits.open(dither2) as hdul2:
        # first masking out bad pixels and objects
        for chip in np.nditer(instrument.chip_layout):
            chip = str(chip)
            # first mask out bad pixels
            if instrument.name == "VIS":
                dq_img1 = hdul1[chip + ".FLG"].data
                dq_img2 = hdul2[chip + ".FLG"].data
                # additional bits: bright star, detected sources
                bits = list(instrument.bad_pix_bits) + [18, 24]
            elif instrument.name == "NISP":
                dq_img1 = hdul1[chip + ".DQ"].data
                dq_img2 = hdul2[chip + ".DQ"].data
                # additional bits: scattered Light, moving Object, Transients; unfortunately no bit for detected sources
                bits = list(instrument.bad_pix_bits) + [19, 20, 21]
            mask1 = np.any(
                [(dq_img1 & 2**bit > 0) for bit in bits],
                axis=0,
            )
            mask2 = np.any(
                [(dq_img2 & 2**bit > 0) for bit in bits],
                axis=0,
            )
            if instrument.name == "NISP":
                obj_mask1, _ = fast_mask(
                    hdul1[chip + ".SCI"].data,
                    estimate_background=True,
                )
                obj_mask2, _ = fast_mask(
                    hdul2[chip + ".SCI"].data,
                    estimate_background=True,
                )
                mask1 = mask1 | obj_mask1
                mask2 = mask2 | obj_mask2
            _mask_in_place(hdul1[chip + ".SCI"], mask1)
            _mask_in_place(hdul2[chip + ".SCI"], mask2)
        # target_hdrs = [hdul2[chip + ".SCI"].header for chip in np.nditer(instrument.chip_layout)]
        # loop over chips in hdul1
        for chip in np.nditer(instrument.chip_layout):
            chip = str(chip)
            hdr = hdul1[chip + ".SCI"].header
            target_chips = get_overlap_chip(hdr, hdul2, instrument.chip_layout)
            if not target_chips:
                continue
            # measure the offset between the chips in dither1 and dither2
            hdus = [hdul2[chip + ".SCI"] for chip in target_chips]
            offset = compute_offset_between_chips(hdul1[chip + ".SCI"], hdus)
            chip_pairs.extend([(chip, target_chip) for target_chip in target_chips])
            offsets.extend(offset)
        dither_id1 = get_dither_id_from_filename(dither1)
        dither_id2 = get_dither_id_from_filename(dither2)
        res = {
            "instrument": instrument,
            "dither pair": (dither_id1, dither_id2),
            "chip pair": chip_pairs,
            "offset": offsets,
        }
        return res


# | export


def measure_offset_per_observation(dir, obsid, instrument, filter):
    """Measure the offset between the overlapping chips among the dithers of one observation.

    Uses multiprocessing to parallelize processing of dither pairs.
    """
    if filter not in instrument.filters:
        raise ValueError(f"Filter {filter} is not available for {instrument.name}.")
    if instrument.name == "VIS":
        filter = "VIS"
    # find the dither files
    dir = Path(dir).expanduser()
    dithers = list(dir.glob(f"**/EUC_*{filter}*{obsid}-*.fits"))
    # form dither pairs
    dither_pairs = form_dither_pairs(dithers)

    if not dither_pairs:
        return []

    # Use multiprocessing to process dither pairs in parallel
    num_processes = min(mp.cpu_count(), len(dither_pairs))
    process_func = partial(measure_offset_per_dither_pair, instrument=instrument)
    with mp.Pool(processes=num_processes) as pool:
        results = pool.map(process_func, dither_pairs)

    # Post-process the results to add additional information
    offset_dicts = []
    for result in results:
        result["obsid"] = obsid
        result["filter"] = filter
        offset_dicts.append(result)

    return offset_dicts

# %% ../../nbs/euclid/continuity.ipynb 8
def solve_for_correction_per_observation(offset_dicts):
    instrument = offset_dicts[0]["instrument"]
    # Flatten the tuples of dither pairs before making the set
    unique_dithers = set(
        dither for offset_dict in offset_dicts for dither in offset_dict["dither pair"]
    )
    solutions_finder_chart = [
        dither + "." + str(chip)
        for dither in unique_dithers
        for chip in np.nditer(instrument.chip_layout)
    ]
    num_solutions = len(solutions_finder_chart)
    a = []
    b = []
    for offset_dict in offset_dicts:
        dither1, dither2 = offset_dict["dither pair"]
        for (chip1, chip2), (offset, offset_err) in zip(
            offset_dict["chip pair"], offset_dict["offset"]
        ):
            if np.isfinite(offset):
                coeff_array = np.zeros(num_solutions)
                idx1 = solutions_finder_chart.index(dither1 + "." + chip1)
                idx2 = solutions_finder_chart.index(dither2 + "." + chip2)
                coeff_array[idx1] = 1
                coeff_array[idx2] = -1
                a.append(coeff_array)
                b.append(-offset)
    a = np.array(a)
    b = np.array(b)
    print("number of equations: ", len(a))
    print("number of unknowns: ", num_solutions)
    solutions, residuals, rank, _ = lstsq(a, b, rcond=None)
    if rank < num_solutions or len(a) < num_solutions:
        residuals = np.linalg.norm(b - a @ solutions)
    print(f"rank: {rank}, residuals: {residuals}")
    # map solutions to the dither chips using the solutions_finder_chart
    mapped_solutions = {
        chart: solution for chart, solution in zip(solutions_finder_chart, solutions)
    }
    return mapped_solutions, residuals / np.sqrt(len(b))


def apply_correction(
    dir, obsid, instrument, filter, solutions, out_dir=None, overwrite=False
):
    if filter not in instrument.filters:
        raise ValueError(f"Filter {filter} is not available for {instrument.name}.")
    if instrument.name == "VIS":
        filter = "VIS"
        target_mag_zpt = 24.56605
        target_pix_scl = 0.1
        zpt_key = "MAGZEROP"
    else:
        target_mag_zpt = 30
        target_pix_scl = 0.3
        zpt_key = "ZPAB"
    dir = Path(dir).expanduser()
    out_dir = Path(out_dir).expanduser() if out_dir else None
    # find the dither files
    dithers = list(dir.glob(f"**/EUC_*{filter}*{obsid}-*.fits"))
    # exlcude short exposures of VIS
    if instrument.name == "VIS":
        dithers = [dither for dither in dithers if "-2" not in dither.name]
    num_processes = min(mp.cpu_count(), len(dithers))
    process_func = partial(
        correct_dither,
        instrument=instrument,
        solutions=solutions,
        target_pix_scl=target_pix_scl,
        target_mag_zpt=target_mag_zpt,
        zpt_key=zpt_key,
        out_dir=out_dir,
        overwrite=overwrite,
    )
    with mp.Pool(processes=num_processes) as pool:
        pool.map(process_func, dithers)


def correct_dither(
    dither,
    instrument,
    solutions,
    target_pix_scl,
    target_mag_zpt,
    zpt_key,
    out_dir=None,
    overwrite=False,
):
    """Apply the discontinuity correction to a dither."""
    dither_id = get_dither_id_from_filename(dither)
    with fits.open(dither) as hdul:
        # loop over chips in hdul
        for chip in np.nditer(instrument.chip_layout):
            chip = str(chip)
            hdr = hdul[chip + ".SCI"].header
            mag_zpt = float(hdr.get(zpt_key))
            eff_pix_scl = compute_pixel_scales(hdr)
            corr = solutions[dither_id + "." + chip]
            corr_arr = (
                corr
                / target_pix_scl**2
                * eff_pix_scl**2
                * 10 ** (0.4 * (mag_zpt - target_mag_zpt))
            )
            hdul[chip + ".SCI"].data += corr_arr
            # update the header
            hdr.add_history(f"Applied discontinuity correction {corr} to {chip}.")
        if out_dir is None:
            out_dir = dither.parent
        if not out_dir.exists():
            out_dir.mkdir(parents=True, exist_ok=True)
        out_fn = out_dir / (dither.stem + "_corr.fits")
        hdul.writeto(out_fn, overwrite=overwrite)
