"""Investigating and removing banding artefacts from a set of observations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/debanding.ipynb.

# %% auto 0
__all__ = ['banding_correction']

# %% ../../nbs/euclid/debanding.ipynb 2
import warnings

import numpy as np
import xarray as xr

from .xarray import xr_fast_mask
from ..filter import sampled_median_filter

# %% ../../nbs/euclid/debanding.ipynb 8
def filter_and_mask_data(data, scale=200):
    """Filter the data to remove large scale variations.
    
    A smoothed, median filtered, version of the data is subtracted from the original data.
    The result is is then masked using an object mask created from the original data.
    The result should a map of the small scale variations in the background.

    The input data should already be masked with NaNs
    """
    smoothed = sampled_median_filter(data, scale, dims=["y", "x"])
    filtered_data = data - smoothed
    mask_params = {
        "nsigma": 2.0,
        "erosion_iterations": 1,
        "dilation_radius": 2.0,
        "dilation_iterations": 2,
    }
    mask = xr_fast_mask(data, mask_params=mask_params, estimate_background=True)
    filtered_data = filtered_data.where(~mask)
    return filtered_data

# %% ../../nbs/euclid/debanding.ipynb 21
def banding_correction(data, rows=True, cols=True, max_size=200):
    if isinstance(data, np.ndarray):
        data = xr.DataArray(data, dims=["y", "x"])
        return_numpy = True
    else:
        return_numpy = False
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", "invalid value encountered in reduce")
        filtered_data = filter_and_mask_data(data, scale=max_size)
        
        if rows:
            med_x = filtered_data.median("x")
            try:
                med_med_x = med_x.median("y")
            except NotImplementedError:
                med_med_x = med_x.as_numpy().median("y")
            med_x -= med_med_x
        if cols:
            med_y = filtered_data.median("y")
            try:
                med_med_y = med_y.median("x")
            except NotImplementedError:
                med_med_y = med_y.as_numpy().median("x")
            med_y -= med_med_y
    correction = med_x + med_y
    try:
        med_correction = correction.median()
    except NotImplementedError:
        med_correction = correction.as_numpy().median()
    correction -= med_correction
    if return_numpy:
        correction = correction.to_numpy()
    return correction
