"""Investigating and removing banding artefacts from a set of observations."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/debanding.ipynb.

# %% auto 0
__all__ = ['banding_correction']

# %% ../../nbs/euclid/debanding.ipynb 7
def mask_data(data):
    mask = xr_fast_mask(data)
    # this currently doesn't work, apparently because of a bug in kerchunk, interpreting the type incorrectly (unsigned int32?)
    # invalid = ds["DQ"]
    # invalid = invalid > 0
    # mask = mask | invalid
    masked_data = data.where(~mask)
    return masked_data

# %% ../../nbs/euclid/debanding.ipynb 8
def filter_data(data, scale=200):
    smoothed = sampled_median_filter(data, scale, dims=["x", "y"])
    filtered_data = data - smoothed
    return filtered_data

# %% ../../nbs/euclid/debanding.ipynb 22
def banding_correction(data, rows=True, cols=True, max_size=200):
    masked_data = mask_data(data)
    filtered_data = filter_data(masked_data, scale=max_size)
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", "invalid value encountered in reduce")
        if rows:
            med_x = filtered_data.median("x")
            try:
                med_med_x = med_x.median("y")
            except NotImplementedError:
                med_med_x = med_x.as_numpy().median("y")
            med_x = med_x - med_med_x
        if cols:
            med_y = filtered_data.median("y")
            try:
                med_med_y = med_y.median("x")
            except NotImplementedError:
                med_med_y = med_y.as_numpy().median("x")
            med_y = med_y - med_med_y
    correction = med_x + med_y
    return correction
