"""Mask sources in a Euclid image prior to ICL measurement."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/mask.ipynb.

# %% auto 0
__all__ = ['calc_sb_threshold', 'create_masks', 'make_mask_plot', 'stack_nir_bands', 'create_combined_nir_mask',
           'create_vis_mask']

# %% ../../nbs/euclid/mask.ipynb 5
from pathlib import Path

import numpy as np
import astropy.units as u
from astropy.io import fits
from astropy.wcs import WCS

from nicl.mask import (
    create_bcg_mask,
    create_icl_mask,
    create_faint_mask,
    create_object_mask,
)
from nicl.utilities import (
    calc_sb_threshold as _calc_sb_threshold,
    get_pixel_scale,
    sb_to_adu,
)

# %% ../../nbs/euclid/mask.ipynb 7
configure_logging(__name__)

# %% ../../nbs/euclid/mask.ipynb 8
plt.style.use("nicl.euclid.v1nicl")

# %% ../../nbs/euclid/mask.ipynb 9
def calc_sb_threshold(
    z,  # cluster redshift
    filter,  # Euclid filter: VIS, Y, J or H
):
    """Determine the ICL surface brightness threshold for a given redshift and Euclid filter."""
    filter = filter.replace("NIR_", "")
    filter = f"Euclid-{filter}.ecsv"
    return _calc_sb_threshold(z, filter)

# %% ../../nbs/euclid/mask.ipynb 11
def create_masks(
    image,  # the image to mask, with bad pixels set to NaN, as a CCDImage or filename
    *,  # the following parameters must be provided as keyword arguments if required
    z=None,  # the cluster redshift for the BCG mask; if None then returned BCG mask is None
    filter=None,  # the filter name for the BCG mask; if None then returned BCG mask is None
    centre_pos=None,  # the position of the BCG/cluster centre; set to False for a non-cluster image
    make_faint_mask=True,  # whether to create a separate object mask in the ICL region
    zeropoint="ZPAB",  # the zeropoint, either as a header keyword or numeric value
):
    """Create BCG, ICL, object and faint masks with default settings for Euclid data.

    These default settings are to be refined.
    """
    if isinstance(image, str):
        image = CCDData.read(image, unit="adu")  # unit does not matter
    # === Bad pixels ===
    badpixel_mask = ~np.isfinite(image)
    # === BCG ===
    if centre_pos is not False and z is not None and filter is not None:
        sb_threshold = calc_sb_threshold(z, filter)
        if isinstance(zeropoint, str):
            zp = image.header[zeropoint] * u.ABmag
        else:
            zp = zeropoint * u.ABmag
        sb_adu_threshold = sb_to_adu(sb_threshold, get_pixel_scale(image), zp)
        bcg_mask = create_bcg_mask(
            image.data,
            sb_threshold=sb_adu_threshold,
            centre_pos=centre_pos,
            wcs=image.wcs,
        )
    else:
        bcg_mask = None
    # === ICL ===
    if centre_pos is not False:
        icl_mask, _ = create_icl_mask(
            image.data,
            centre_pos=centre_pos,
            wcs=image.wcs,
            nsigma=ICL_NSIGMA,
            smooth_sigma=ICL_SMOOTH_SIGMA,
            bkg_box_size=ICL_BKG_BOX_SIZE,
            bkg_filter_size=ICL_BKG_FILTER_SIZE,
            dilation_radius=ICL_DILATION_RADIUS,
            median_filter=ICL_MEDIAN_FILTER,
        )
    else:
        icl_mask = None
    # === Regular objects ===
    if make_faint_mask:
        # In this case, we exclude objects under the ICL mask,
        # as these will be included in the faint mask
        object_mask, bkg, threshold, centre_mask = create_object_mask(
            image.data,
            exclude_mask=icl_mask,
            growth=REGULAR_GROWTH,
            detection_params=REGULAR_DETECTION_PARAMS,
        )
    else:
        # In this case, we only exclude the object at the central position
        object_mask, bkg, threshold, centre_mask = create_object_mask(
            image.data,
            exclude_position=centre_pos,
            wcs=image.wcs,
            growth=REGULAR_GROWTH,
            detection_params=REGULAR_DETECTION_PARAMS,
        )
    # === Faint objects (under ICL) ===
    if centre_pos is not False and make_faint_mask:
        faint_mask, faint_bkg, faint_threshold = create_faint_mask(
            image.data,
            include_mask=centre_mask,
            exclude_position=centre_pos,
            wcs=image.wcs,
            growth=FAINT_GROWTH,
            detection_params=FAINT_DETECTION_PARAMS,
            bkg_sigma=FAINT_BKG_SIGMA,
        )
    else:
        faint_mask = None
    output_masks = {
        "badpixel": badpixel_mask,
        "bcg": bcg_mask,
        "icl": icl_mask,
        "object": object_mask,
        "faint": faint_mask,
    }
    return output_masks

# %% ../../nbs/euclid/mask.ipynb 13
def make_mask_plot(image, masks, output_dir=None, label=None):
    for mask_name, mask in masks.items():
        plot_mask(image, mask, detail=True)
        if output_dir:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)
            prefix = f"{label}_" if label else ""
            plt.savefig(output_dir / f"{prefix}{mask_name}_mask.pdf")
            plt.close()

# %% ../../nbs/euclid/mask.ipynb 14
def stack_nir_bands(H_filename, J_filename, Y_filename, output_dir=None, label=None):
    """Stack NIR images and optionally save to disk."""
    logger = logging.getLogger(__name__)
    logger.info(f"Stacking images: {H_filename}, {J_filename}, {Y_filename}")
    filenames = {"H": H_filename, "J": J_filename, "Y": Y_filename}
    images = {band: fits.getdata(filenames[band]) for band in ["H", "J", "Y"]}
    logger.debug(
        f"Shapes: H={images['H'].shape}, J={images['J'].shape}, Y={images['Y'].shape}"
    )
    logger.debug(
        f"NaN Count: H={np.isnan(images['H']).sum()}, J={np.isnan(images['J']).sum()}, Y={np.isnan(images['Y']).sum()}"
    )

    # create global mask
    masks = {band: ~np.isfinite(images[band]) for band in ["H", "J", "Y"]}
    global_mask = masks["H"] | masks["J"] | masks["Y"]
    for band in ["H", "J", "Y"]:
        images[band][global_mask] = np.nan

    # combined image
    bandwidth = {"H": 499.9, "J": 399.4, "Y": 262.7}
    total_bandwidth = bandwidth["H"] + bandwidth["J"] + bandwidth["Y"]
    combined_image = (
        (images["H"] * bandwidth["H"])
        + (images["J"] * bandwidth["J"])
        + (images["Y"] * bandwidth["Y"])
    ) / total_bandwidth
    logger.debug(
        f"Combined Image: Min={np.nanmin(combined_image)}, Max={np.nanmax(combined_image)}, NaN Count={np.isnan(combined_image).sum()}"
    )

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        header = WCS(fits.getheader(H_filename)).to_header()
        fits.writeto(
            output_dir / f"{prefix}HJY_combined.fits",
            combined_image,
            header=header,
            overwrite=True,
        )

    return combined_image


def create_combined_nir_mask(
    H_filename, J_filename, Y_filename, output_dir=None, label=None
):
    """Create a combined NIR mask for use when measuring ICL."""
    filenames = {"H": H_filename, "J": J_filename, "Y": Y_filename}
    images = dict()
    for band in ["H", "J", "Y"]:
        image = fits.getdata(filenames[band])
        m = create_masks(image, create_faint_mask=False)
        mask_for_background = m["badpixel"] | m["icl"] | m["object"]
        bkg = get_background(
            image,
            mask=mask_for_background,
            box_size=NIR_STACK_BKG_BOX_SIZE,
            filter_size=NIR_STACK_BKG_FILTER_SIZE,
        )
        images[band] = image - bkg
    combined_image = stack_nir_bands(images["H"], images["J"], images["Y"])
    masks = create_masks(combined_image)
    mask_for_background = masks["badpixel"] | masks["icl"] | masks["object"]
    mask_for_measurement = masks["badpixel"] | masks["object"] | masks["faint"]

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        header = WCS(fits.getheader(H_filename)).to_header()
        fits.writeto(
            output_dir / f"{prefix}NIR_background_mask.fits",
            mask_for_background,
            header=header,
            overwrite=True,
        )
        fits.writeto(
            output_dir / f"{prefix}NIR_measurement_mask.fits",
            mask_for_measurement,
            header=header,
            overwrite=True,
        )

    return mask_for_background, mask_for_measurement


def create_vis_mask(VIS_filename, output_dir=None, label=None):
    """Create a VIS mask for use when measuring ICL."""
    image = fits.getdata(VIS_filename)
    masks = create_masks(image)
    mask_for_background = masks["badpixel"] | masks["icl"] | masks["object"]
    mask_for_measurement = masks["badpixel"] | masks["object"] | masks["faint"]

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        header = WCS(fits.getheader(VIS_filename)).to_header()
        fits.writeto(
            output_dir / f"{prefix}VIS_background_mask.fits",
            mask_for_background,
            header=header,
            overwrite=True,
        )
        fits.writeto(
            output_dir / f"{prefix}VIS_measurement_mask.fits",
            mask_for_measurement,
            header=header,
            overwrite=True,
        )

    return mask_for_measurement
