"""Mask sources in a Euclid image."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/mask.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/euclid/mask.ipynb 2
# | exporti


# %% ../../nbs/euclid/mask.ipynb 3
# | export

