"""Mask sources in a Euclid image prior to ICL measurement."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/mask.ipynb.

# %% auto 0
__all__ = ['ICL_NSIGMA', 'ICL_SMOOTH_SIGMA', 'ICL_BKG_BOX_SIZE', 'ICL_BKG_FILTER_SIZE', 'ICL_DILATION_RADIUS',
           'ICL_MEDIAN_FILTER', 'REGULAR_DETECTION_PARAMS', 'REGULAR_GROWTH', 'FAINT_DETECTION_PARAMS', 'FAINT_GROWTH',
           'FAINT_BKG_SIGMA', 'NIR_STACK_BKG_BOX_SIZE', 'NIR_STACK_BKG_FILTER_SIZE', 'calc_sb_threshold',
           'create_masks', 'make_mask_plot', 'stack_nir_bands', 'create_combined_nir_mask', 'create_vis_mask']

# %% ../../nbs/euclid/mask.ipynb 4
import logging
from pathlib import Path

import astropy.units as u
import matplotlib.pyplot as plt
import numpy as np
from astropy.io import fits
from astropy.nddata import CCDData

from nicl.background import get_background
from nicl.mask import (
    create_bcg_mask,
    create_faint_mask,
    create_icl_mask,
    create_object_mask,
    plot_mask,
)
from nicl.utilities import (
    calc_sb_threshold as _calc_sb_threshold,
)
from nicl.utilities import (
    get_pixel_scale,
    sb_to_adu,
)

# %% ../../nbs/euclid/mask.ipynb 6
plt.style.use("nicl.euclid.v1nicl")

# %% ../../nbs/euclid/mask.ipynb 7
def calc_sb_threshold(
    z,  # cluster redshift
    filter,  # Euclid filter: VIS, Y, J or H
):
    """Determine the ICL surface brightness threshold for a given redshift and Euclid filter."""
    filter = filter.replace("NIR_", "")
    filter = f"Euclid-{filter}.ecsv"
    return _calc_sb_threshold(z, filter)

# %% ../../nbs/euclid/mask.ipynb 8
ICL_NSIGMA = 2
ICL_SMOOTH_SIGMA = 10.0
ICL_BKG_BOX_SIZE = 300
ICL_BKG_FILTER_SIZE = 3
ICL_DILATION_RADIUS = 100
ICL_MEDIAN_FILTER = True
REGULAR_DETECTION_PARAMS = {
    "nsigma": 3.0,
    "background": 0.0,
    "smooth_sigma": 1.0,
    "npixels": 5,
    "nlevels": 32,
    "contrast": 0.01,
    "bkg_box_size": 500,
    "bkg_filter_size": 3,
}
REGULAR_GROWTH = 0.5
FAINT_DETECTION_PARAMS = {
    "nsigma": 2.0,
    "smooth_sigma": 1.0,
    "npixels": 5,
    "nlevels": 128,
    "contrast": 0.001,
}
FAINT_GROWTH = 0.25
FAINT_BKG_SIGMA = 50.0
NIR_STACK_BKG_BOX_SIZE = 300
NIR_STACK_BKG_FILTER_SIZE = 3

# %% ../../nbs/euclid/mask.ipynb 9
def create_masks(
    image,  # the image to mask, with bad pixels set to NaN, as a CCDImage or filename
    *,  # the following parameters must be provided as keyword arguments if required
    z=None,  # the cluster redshift for the BCG mask; if None then returned BCG mask is None
    filter=None,  # the filter name for the BCG mask; if None then returned BCG mask is None
    centre_pos=None,  # the position of the BCG/cluster centre; set to False for a non-cluster image
    make_faint_mask=True,  # whether to create a separate object mask in the ICL region
    zeropoint="ZPAB",  # the zeropoint, either as a header keyword or numeric value
    ICL_BKG_BOX_SIZE=300,
):
    """Create BCG, ICL, object and faint masks with default settings for Euclid data.

    These default settings are to be refined.
    """
    if isinstance(image, str):
        image = CCDData.read(image, unit="adu")  # unit does not matter
    # === Bad pixels ===
    badpixel_mask = ~np.isfinite(image)
    # === BCG ===
    if centre_pos is not False and z is not None and filter is not None:
        sb_threshold = calc_sb_threshold(z, filter)
        if isinstance(zeropoint, str):
            zp = image.header[zeropoint] * u.ABmag
        else:
            zp = zeropoint * u.ABmag
        sb_adu_threshold = sb_to_adu(sb_threshold, get_pixel_scale(image), zp)
        bcg_mask = create_bcg_mask(
            image.data,
            sb_threshold=sb_adu_threshold,
            centre_pos=centre_pos,
            wcs=image.wcs,
        )
    else:
        bcg_mask = None
    # === ICL ===
    if centre_pos is not False:
        icl_mask, smooth_im = create_icl_mask(
            image.data,
            centre_pos=centre_pos,
            wcs=image.wcs,
            nsigma=ICL_NSIGMA,
            smooth_sigma=ICL_SMOOTH_SIGMA,
            bkg_box_size=ICL_BKG_BOX_SIZE,
            bkg_filter_size=ICL_BKG_FILTER_SIZE,
            dilation_radius=ICL_DILATION_RADIUS,
            median_filter=ICL_MEDIAN_FILTER,
        )
    else:
        icl_mask = None
    # === Regular objects ===
    if make_faint_mask:
        # In this case, we exclude objects under the ICL mask,
        # as these will be included in the faint mask
        object_mask, bkg, threshold, centre_mask = create_object_mask(
            image.data,
            exclude_mask=icl_mask,
            growth=REGULAR_GROWTH,
            detection_params=REGULAR_DETECTION_PARAMS,
        )
    else:
        # In this case, we only exclude the object at the central position
        object_mask, bkg, threshold, centre_mask = create_object_mask(
            image.data,
            exclude_position=centre_pos,
            wcs=image.wcs,
            growth=REGULAR_GROWTH,
            detection_params=REGULAR_DETECTION_PARAMS,
        )
    # === Faint objects (under ICL) ===
    if centre_pos is not False and make_faint_mask:
        faint_mask, faint_bkg, faint_threshold = create_faint_mask(
            image.data,
            include_mask=centre_mask,
            exclude_position=centre_pos,
            wcs=image.wcs,
            growth=FAINT_GROWTH,
            detection_params=FAINT_DETECTION_PARAMS,
            bkg_sigma=FAINT_BKG_SIGMA,
        )
    else:
        faint_mask = None
    output_masks = {
        "badpixel": badpixel_mask,
        "bcg": bcg_mask,
        "icl": icl_mask,
        "object": object_mask,
        "faint": faint_mask,
    }
    return output_masks

# %% ../../nbs/euclid/mask.ipynb 11
def make_mask_plot(image, masks, output_dir=None, label=None):
    for mask_name, mask in masks.items():
        plot_mask(image, mask, detail=True)
        if output_dir:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)
            prefix = f"{label}_" if label else ""
            plt.savefig(output_dir / f"{prefix}{mask_name}_mask.pdf")
            plt.close()

# %% ../../nbs/euclid/mask.ipynb 12
def stack_nir_bands(H_filename, J_filename, Y_filename, output_dir=None, label=None):
    """Stack NIR images and optionally save to disk. Returns a CCDData object."""
    logger = logging.getLogger(__name__)
    logger.info(f"Stacking images: {H_filename}, {J_filename}, {Y_filename}")

    # Reading images as CCDData to preserve WCS
    H = CCDData.read(H_filename, unit="adu")
    J = CCDData.read(J_filename, unit="adu")
    Y = CCDData.read(Y_filename, unit="adu")

    images = {"H": H.data, "J": J.data, "Y": Y.data}
    masks = {band: ~np.isfinite(images[band]) for band in ["H", "J", "Y"]}
    global_mask = masks["H"] | masks["J"] | masks["Y"]

    for band in ["H", "J", "Y"]:
        images[band][global_mask] = np.nan

    bandwidth = {"H": 499.9, "J": 399.4, "Y": 262.7}
    total_bandwidth = sum(bandwidth.values())

    combined_image = (
        (images["H"] * bandwidth["H"])
        + (images["J"] * bandwidth["J"])
        + (images["Y"] * bandwidth["Y"])
    ) / total_bandwidth

    logger.debug(
        f"Combined Image: Min={np.nanmin(combined_image)}, Max={np.nanmax(combined_image)}, NaN Count={np.isnan(combined_image).sum()}"
    )

    # Using H-band WCS as reference
    combined_ccd = CCDData(combined_image, unit="adu", wcs=H.wcs)

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        header = combined_ccd.wcs.to_header()
        fits.writeto(
            output_dir / f"{prefix}HJY_combined.fits",
            combined_ccd.data,
            header=header,
            overwrite=True,
        )

    return combined_ccd


def create_combined_nir_mask(
    H_filename,
    J_filename,
    Y_filename,
    output_dir=None,
    label=None,
    centre_pos=None,
    redshift=None,
    filter=None,
    zeropoint=23.9,
    ICL_BKG_BOX_SIZE=300,
    NIR_STACK_BKG_BOX_SIZE=300,
):
    """Create a combined NIR mask for use when measuring ICL."""
    filenames = {"H": H_filename, "J": J_filename, "Y": Y_filename}
    images = {}

    for band in ["H", "J", "Y"]:
        image = CCDData.read(filenames[band], unit="adu")

        m = create_masks(
            image,
            make_faint_mask=False,
            centre_pos=centre_pos,
            z=redshift,
            filter=filter,
            zeropoint=23.9,
            ICL_BKG_BOX_SIZE=ICL_BKG_BOX_SIZE,
        )

        if centre_pos is not False:
            mask_for_background = m["badpixel"] | m["icl"] | m["object"]

        else:
            mask_for_background = m["badpixel"] | m["object"]

        bkg = get_background(
            image.data,
            mask=mask_for_background,
            box_size=NIR_STACK_BKG_BOX_SIZE,
            filter_size=NIR_STACK_BKG_FILTER_SIZE,
        )

        image_bkg_sub = image.data - bkg.background
        images[band] = image_bkg_sub

        # Saving temp background-subtracted image
        temp_filename = f"_temp_bkgsub_{band}.fits"
        temp_ccd = CCDData(image_bkg_sub, unit="adu", wcs=image.wcs)
        temp_ccd.write(temp_filename, overwrite=True)
        filenames[band] = temp_filename

    # Now pass temp files to stacking function
    print("Proceeding to stack_nir_bands...")
    combined_ccd = stack_nir_bands(
        filenames["H"], filenames["J"], filenames["Y"], output_dir=None, label=None
    )
    print("stack_nir_bands is complete...")

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        header = combined_ccd.wcs.to_header()

        fits.writeto(
            output_dir / f"{prefix}NIR_YJH_COADDED.fits",
            combined_ccd.data,
            header=header,
            overwrite=True,
        )
        print("Coadded image is saved.")

    print("Masking the coadded image...")

    masks = create_masks(
        combined_ccd, centre_pos=centre_pos, z=redshift, filter=filter, zeropoint=23.9
    )

    if centre_pos is not False:
        mask_for_background = masks["badpixel"] | masks["icl"] | masks["object"]
    else:
        mask_for_background = masks["badpixel"] | masks["object"]

    faint_mask = (
        masks["faint"]
        if masks["faint"] is not None
        else np.zeros_like(masks["object"], dtype=bool)
    )
    mask_for_measurement = masks["badpixel"] | masks["object"] | faint_mask

    print("Masks are generated...")

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        header = combined_ccd.wcs.to_header()

        fits.writeto(
            output_dir / f"{prefix}NIR_background_mask.fits",
            mask_for_background.astype("uint8"),
            header=header,
            overwrite=True,
        )
        fits.writeto(
            output_dir / f"{prefix}NIR_measurement_mask.fits",
            mask_for_measurement.astype("uint8"),
            header=header,
            overwrite=True,
        )

    # Cleanup temp files
    for band in ["H", "J", "Y"]:
        temp_file = filenames[band]
        if "_temp_bkgsub_" in temp_file and Path(temp_file).exists():
            Path(temp_file).unlink()

    return mask_for_background, mask_for_measurement, combined_ccd.data


def create_vis_mask(
    VIS_filename,
    output_dir=None,
    label=None,
    centre_pos=None,
    redshift=None,
    filter=None,
    ICL_BKG_BOX_SIZE=300,
):
    """Create a VIS mask for use when measuring ICL."""
    image = CCDData.read(VIS_filename, unit="adu")
    masks = create_masks(
        image,
        centre_pos=centre_pos,
        z=redshift,
        filter=filter,
        zeropoint=23.9,
        ICL_BKG_BOX_SIZE=ICL_BKG_BOX_SIZE,
    )

    if centre_pos is not False:
        mask_for_background = masks["badpixel"] | masks["icl"] | masks["object"]
    else:
        mask_for_background = masks["badpixel"] | masks["object"]

    faint_mask = (
        masks["faint"]
        if masks["faint"] is not None
        else np.zeros_like(masks["object"], dtype=bool)
    )
    mask_for_measurement = masks["badpixel"] | masks["object"] | faint_mask

    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        prefix = f"{label}_" if label else ""
        header = image.wcs.to_header()

        fits.writeto(
            output_dir / f"{prefix}VIS_background_mask.fits",
            mask_for_background.astype("uint8"),
            header=header,
            overwrite=True,
        )
        fits.writeto(
            output_dir / f"{prefix}VIS_measurement_mask.fits",
            mask_for_measurement.astype("uint8"),
            header=header,
            overwrite=True,
        )

    return mask_for_measurement, mask_for_background
