"""Removal persistence features from calibrated Euclid images"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/persistence.ipynb.

# %% auto 0
__all__ = ['estimate_persistence_decay', 'correct_persistence']

# %% ../../nbs/euclid/persistence.ipynb 3
import numpy as np
import os
from astropy.io import fits

from nicl.euclid.utilities import (
    get_nisp_images_for_observation,
    get_primary_header,
    get_persistence_mask,
    get_invalid_mask,
    get_rms,
    fits_append,
    remove_if_necessary,
)

# %% ../../nbs/euclid/persistence.ipynb 12
def estimate_persistence_decay(
    minimum_images,  # the minimum estimates of the persistence
    dt_lp_images,  # the times since the last persistence feature appeared
    ext,  # the image extension
    debug=False,  # print some useful debugging information and save intermediate images
    primary_header=None,  # the primary header for debug images
    outpath=None,  # path at which to save debug images
):
    obs_ids = []
    mean_img = None
    for image_id in minimum_images:
        obs_ids.append(image_id[0])
        img = minimum_images[image_id]
        if mean_img is None:
            mean_img = img
        else:
            mean_img += img
    mean_img /= len(minimum_images)
    obs_id = np.median(obs_ids)
    bkg = median_filter(mean_img, 25)
    mean_img_bkg_sub = mean_img - bkg

    threshold = detect_threshold(mean_img_bkg_sub, nsigma=3.0)
    kernel = make_2dgaussian_kernel(2.0, size=7)
    det_img = convolve(mean_img_bkg_sub, kernel)
    segm = detect_sources(
        data=det_img,
        threshold=threshold,
        npixels=25,
    )
    segm_deblend = deblend_sources(
        det_img,
        segm,
        npixels=25,
        nlevels=32,
        contrast=0.1,
        progress_bar=True,
    )
    if debug:
        out_fn = os.path.join(outpath, f"segm_{obs_id}.fits")
        fits_append(out_fn, segm.data, ext, primary_header)
        out_fn = os.path.join(outpath, f"segd_{obs_id}.fits")
        fits_append(out_fn, segm_deblend.data, ext, primary_header)

    segm_fluxes = []
    segm_dt_lp = []
    for image_id in minimum_images:
        img = minimum_images[image_id]
        cat = SourceCatalog(img, segm_deblend)
        segm_fluxes.append(cat.segment_flux)
        dt = dt_lp_images[image_id]
        cat = SourceCatalog(dt, segm_deblend)
        segm_dt_lp.append(cat.segment_flux / cat.area)
    segm_fluxes = np.array(segm_fluxes)
    segm_fluxes = np.maximum(segm_fluxes, 1)
    segm_log_fluxes = np.log10(segm_fluxes)
    segm_dt_lp = np.array(segm_dt_lp)

    decay_fits = {}
    clipped = {}
    for i in range(segm_dt_lp.shape[1]):
        x = segm_dt_lp[:, i]
        y = segm_log_fluxes[:, i]
        decay_fits[i], clipped[i] = fit_persistence_decay(x, y)
    slope, intercept = np.transpose(
        [(d.slope.value, d.intercept.value) for d in decay_fits.values()]
    )

    if debug:
        brightest = segm_fluxes.max(axis=0).argsort()[-10:]
        x = np.array([0.0, 0.1])
        fig, ax = plt.subplots(2)
        for b in brightest:
            p = decay_fits[b]
            points = plt.plot(segm_dt_lp[:, b], segm_log_fluxes[:, b], ".")
            ax[0].plot(x, p(x), "-", color=points[0].get_color())
        ax[0].xlim(xmin=-0.02, xmax=0.12)
        ax[0].ylim(2.5, 5)
        ax[0].set_xlabel("time since persistence flagged")
        ax[0].set_ylabel("$\\log_10$ flux in persistence feature")
        ax[1].hist(slope, bins=100, range=(-20, 10))
        ax[0].set_xlabel("log slope of persistence decay")
        out_fn = os.path.join(outpath, f"decay_{obs_id}_{ext}.pdf")
        fig.savefig(out_fn)

    average_slope = np.nanmedian(slope)
    return average_slope

# %% ../../nbs/euclid/persistence.ipynb 13
def correct_persistence(
    obs_id,
    path,
    outpath=None,
    detector=None,
    estimate_decay=False,
    use_estimated_decay=False,
    debug=False,
    assumed_decay_slope=9,
):
    if use_estimated_decay:
        estimate_decay = True
    path = os.path.abspath(os.path.expanduser(path))
    if outpath is not None:
        outpath = os.path.abspath(os.path.expanduser(outpath))
        if path == outpath:
            raise FileExistsError("outpath cannot be the same as the path")
    else:
        outpath = os.path.join(path, "persistence")
    image_info = get_nisp_images_for_observation(2070, n_prior=1, n_after=1, path=path)
    primary_header = get_primary_header(image_info.filename) if debug else None
    if detector is None:
        dets = [f"DET{i}{j}" for j in range(1, 5) for i in range(1, 5)]
    else:
        dets = [f"DET{detector}"]
    sci_exts = [f"{d}.SCI" for d in dets]
    if os.path.isdir(outpath):
        for img_name in ("min", "lp", "dt_lp", "dt", "img", "corr", "pers"):
            remove_if_necessary(outpath, f"{img_name}_{obs_id}*.fits")
        for fn in image_info.filename:
            remove_if_necessary(outpath, os.path.basename(fn))
    else:
        os.makedirs(outpath)
    obs_image_info = image_info[image_info.obs_id == obs_id]
    for ext in sci_exts:
        minimum_images, dt_lp_images, dt_images = calc_rolling_minimum(
            obs_id,
            image_info,
            ext=ext,
            debug=debug,
            primary_header=primary_header,
            outpath=outpath,
        )
        if estimate_decay:
            slope = estimate_persistence_decay(
                minimum_images, dt_lp_images, ext=ext, debug=debug, outpath=outpath
            )
            print(f"Estimated persistence decay slope ({ext}): {slope:.2f}")
            if not use_estimated_decay:
                slope = assumed_decay_slope
        else:
            slope = assumed_decay_slope
        persistence_images = calc_persistence_correction(
            minimum_images,
            dt_images,
            ext=ext,
            debug=False,
            primary_header=primary_header,
            outpath=outpath,
            decay_slope=slope,
        )
        apply_persistence_correction(
            obs_image_info, persistence_images, outpath=outpath
        )
