"""Create images for use in testing the pipeline."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/testing.ipynb.

# %% auto 0
__all__ = ['outpath', 'get_bcg_icl_mags', 'create_basic_test_images']

# %% ../../nbs/euclid/testing.ipynb 3
import astropy.units as u
import galsim
import numpy as np
from astropy.io import fits

from .. import ezgal
from .data_access import default_data_path
from ..utilities import physical_to_angular

# %% ../../nbs/euclid/testing.ipynb 5
outpath = default_data_path("test_images")

# %% ../../nbs/euclid/testing.ipynb 6
def get_bcg_icl_mags(z=0.1):
    bcg_I_absmag = -25.0
    icl_I_absmag = -25.5
    bcg_zf = 3.0
    icl_zf = 1.0
    model = ezgal.model("bc03_ssp_z_0.02_chab.model")
    model.set_cosmology(Om=0.3, Ol=0.7, h=0.70, w=-1)
    distmod = model.get_distance_moduli(z, 1)
    bands = {band: f"Euclid-{band}.ecsv" for band in ["Y", "J", "H", "VIS"]}

    def calc_mags(zf, I_absmag):
        mags = {
            band: model.get_observed_absolute_mags(zf=zf, filters=filt, zs=z)
            for band, filt in bands.items()
        }
        model_I_absmag = model.get_absolute_mags(zf=zf, filters="I", zs=z)
        delta_mag = I_absmag - model_I_absmag
        mags = {band: round(mags[band] + delta_mag + distmod, 2) for band in mags}
        return mags

    mags_bcg = calc_mags(bcg_zf, bcg_I_absmag)
    mags_icl = calc_mags(icl_zf, icl_I_absmag)
    return mags_bcg, mags_icl


def _mag_to_flux(mag, zp):
    return 10 ** (-(mag - zp) / 2.5)

# %% ../../nbs/euclid/testing.ipynb 8
def create_basic_test_images(z=0.1):
    path = default_data_path("Q1_R1_clusters_test", "MCXCJ1754.6+6803")
    hdul = fits.open(path / "EUC_NIR_W-STK_H-MCXCJ1754.6+6803.fits")
    shape = hdul["SCI"].shape
    zp = 23.9  # zeropoint for mJy
    rms = dict(H=0.023, J=0.023, Y=0.023, VIS=0.023)
    source_noise_level = 0.05  # relative noise added to sources

    pixscale = 0.3 * u.arcsec / u.pix

    bcg_appmags, icl_appmags = get_bcg_icl_mags(z)

    bcg_re = (physical_to_angular(22.6 * u.kpc, z) / pixscale).to_value(u.pix)
    bcg_n = 4.6
    bcg_q = 0.6
    bcg_theta = 30

    bcg = galsim.Sersic(n=bcg_n, half_light_radius=bcg_re, flux=1)
    bcg_shape = galsim.Shear(q=bcg_q, beta=bcg_theta * galsim.degrees)
    bcg = bcg.shear(bcg_shape)

    icl_re = (physical_to_angular(189.5 * u.kpc, z) / pixscale).to_value(u.pix)
    icl_n = 0.76
    icl_q = 0.6
    icl_theta = 60

    icl = galsim.Sersic(n=icl_n, half_light_radius=icl_re, flux=1)
    icl_shape = galsim.Shear(q=icl_q, beta=icl_theta * galsim.degrees)
    icl = icl.shear(icl_shape)

    print(f"bcg_appmags: {bcg_appmags}")
    print(f"icl_appmags: {icl_appmags}")
    print(f"bcg_re: {bcg_re:.2f} pixels")
    print(f"icl_re: {icl_re:.2f} pixels")

    basic_test_outpath = outpath / "basic_test"
    basic_test_outpath.mkdir(parents=True, exist_ok=True)
    image = galsim.ImageF(*shape)

    for band in ["H", "J", "Y", "VIS"]:
        hdul["RMS"].data[:] = rms[band]
        bcg_flux = _mag_to_flux(bcg_appmags[band], zp)
        icl_flux = _mag_to_flux(icl_appmags[band], zp)
        print(f"{band} bcg_flux: {bcg_flux}")
        print(f"{band} icl_flux: {icl_flux}")
        print(f"{band} bcg_flux + icl_flux: {bcg_flux + icl_flux}")
        cluster = bcg * bcg_flux + icl * icl_flux
        cluster.drawImage(image, method="no_pixel")
        hdul["SCI"].data[:] = image.array
        hdul.writeto(
            basic_test_outpath / f"cluster_{band}_no_noise.fits", overwrite=True
        )
        background_noise = np.random.normal(scale=rms[band], size=shape)
        source_noise = np.random.normal(
            scale=np.maximum(0, source_noise_level * image.array), size=shape
        )
        hdul["SCI"].data[:] += source_noise + background_noise
        hdul.writeto(basic_test_outpath / f"cluster_{band}.fits", overwrite=True)
