"""Utilities for handling Euclid FITS images as xarray Datasets, using dask for efficient computation and memory usage."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/euclid/xarray.ipynb.

# %% auto 0
__all__ = ['create_zarr_ref_from_fits', 'open_zarr_ref_as_dataset', 'open_fits_as_dataset', 'write_da_to_fits', 'load_zarr_ref',
           'load_wcs_from_zarr', 'create_all_zarr_refs', 'read_all_zarr_refs', 'xr_fast_mask']

# %% ../../nbs/euclid/xarray.ipynb 2
import json
from pathlib import Path
from warnings import catch_warnings, filterwarnings

import numpy as np
import pandas as pd
import fsspec
import numcodecs
import xarray as xr
import zarr
from astropy.io import fits
from astropy.io.fits import HDUList, ImageHDU, PrimaryHDU
from astropy.wcs import WCS
from fsspec.implementations.reference import LazyReferenceMapper
from kerchunk.codecs import AsciiTableCodec, VarArrCodec
from kerchunk.combine import MultiZarrToZarr
from tqdm import tqdm

from ..mask import fast_mask
from nicl.euclid.utilities import (
    get_dither_id_from_filename,
    get_filter_from_filename,
    get_obs_id_from_filename,
    get_tile_index_from_filename,
)

# %% ../../nbs/euclid/xarray.ipynb 4
def _rename(refs, new_name):
    """Rename the zarray in a kerchunk json reference."""
    new_refs = {}
    for key in refs.keys():
        if "/" in key:
            parts = key[key.find("/") + 1 :]
            new_key = f"{new_name}/{parts}"
            new_refs[new_key] = refs[key]
    return new_refs

# %% ../../nbs/euclid/xarray.ipynb 5
def _get_ext_type(x):
    return x.split(".")[-1] if "." in x else None


def _get_ext_det(x):
    return ".".join(x.split(".")[:-1]) if "." in x else x

# %% ../../nbs/euclid/xarray.ipynb 6
# Code vendored from kerchunk.fits and adapted for speed with very large files

BITPIX2DTYPE = {
    8: ">u1",
    16: ">i2",
    32: ">i4",
    64: ">i8",
    -32: ">f4",
    -64: ">f8",
}  # always bigendian


def infer_dtype_info(attrs):
    """Infer the dtype of a FITS file from the header."""
    bitpix = attrs["BITPIX"]
    bzero = attrs.get("BZERO")
    stored_dtype = BITPIX2DTYPE[bitpix]
    dtype = stored_dtype
    if bitpix == 64 and bzero == 2**63:
        dtype = ">u8"
    if bitpix == 32 and bzero == 2**31:
        dtype = ">u4"
    elif bitpix == 16 and bzero == 2**15:
        dtype = ">u2"
    return dtype, stored_dtype


def process_file(
    url,
    extension,
    storage_options=None,
    out=None,
    hdu=None,
    infile=None,
):
    """
    Create JSON references for a single FITS file as a zarr group

    Parameters
    ----------
    url: str
        Where the file is
    extension: str
        The extension name
    storage_options: dict
        How to load that file (passed to fsspec)
    out: dict-like or None
        This allows you to supply an fsspec.implementations.reference.LazyReferenceMapper
        to write out parquet as the references get filled, or some other dictionary-like class
        to customise how references get stored
    hdu: HDU or None
        An open FITS HDU to process
    infile: HDUList or None
        An open FITS file to process


    Returns
    -------
    dict of the references and the header
    """
    from astropy.io import fits

    storage_options = storage_options or {}
    out = out or {}
    g = zarr.open(out)

    with fsspec.open(url, mode="rb", **storage_options) as f:
        if hdu is None and infile is None:
            infile = fits.open(f, do_not_scale_image_data=True)
        if hdu is None:
            hdu = infile[extension]
        hdr = hdu.header
        hdr.__str__()  # causes fixing of invalid cards
        attrs = dict(hdr)
        kwargs = {}
        if hdu.is_image:
            # for images/cubes (i.e., ndarrays with simple type)
            nax = attrs["NAXIS"]
            shape = tuple(int(attrs[f"NAXIS{i}"]) for i in range(nax, 0, -1))
            dtype, stored_dtype = infer_dtype_info(attrs)
            length = np.dtype(dtype).itemsize
            for s in shape:
                length *= s

            if "BSCALE" in attrs or "BZERO" in attrs:
                kwargs["filters"] = [
                    numcodecs.FixedScaleOffset(
                        offset=float(attrs.get("BZERO", 0)),
                        scale=float(attrs.get("BSCALE", 1)),
                        astype=dtype,
                        dtype=np.dtype(stored_dtype).type,
                    )
                ]
            else:
                kwargs["filters"] = None
        elif isinstance(hdu, fits.hdu.table.TableHDU):
            # ascii table
            spans = hdu.columns._spans
            outdtype = [
                [name, hdu.columns[name].format.recformat]
                for name in hdu.columns.names
            ]
            indtypes = [
                [name, f"S{i + 1}"] for name, i in zip(hdu.columns.names, spans)
            ]
            nrows = int(attrs["NAXIS2"])
            shape = (nrows,)
            kwargs["filters"] = [AsciiTableCodec(indtypes, outdtype)]
            dtype = [tuple(d) for d in outdtype]
            length = (sum(spans) + len(spans)) * nrows
        elif isinstance(hdu, fits.hdu.table.BinTableHDU):
            # binary table
            dtype = hdu.columns.dtype.newbyteorder(">")  # always big endian
            nrows = int(attrs["NAXIS2"])
            shape = (nrows,)
            # if hdu.fileinfo()["datSpan"] > length
            if any(_.format.startswith(("P", "Q")) for _ in hdu.columns):
                # contains var fields
                length = hdu.fileinfo()["datSpan"]
                dt2 = [
                    (name, "O")
                    if hdu.columns[name].format.startswith(("P", "Q"))
                    else (name, str(dtype[name].base))
                    + ((dtype[name].shape,) if dtype[name].shape else ())
                    for name in dtype.names
                ]
                types = {
                    name: hdu.columns[name].format[1]
                    for name in dtype.names
                    if hdu.columns[name].format.startswith(("P", "Q"))
                }
                kwargs["object_codec"] = VarArrCodec(
                    str(dtype), str(dt2), nrows, types
                )
                dtype = dt2
            else:
                length = dtype.itemsize * nrows
                kwargs["filters"] = None
        else:
            print(f"Unknown extension type: {hdu}")
        # one chunk for whole thing.
        # TODO: we could sub-chunk on biggest dimension
        name = hdu.name or str(extension)
        arr = g.empty(
            name, dtype=dtype, shape=shape, chunks=shape, compression=None, **kwargs
        )
        arr.attrs.update(
            {
                k: str(v) if not isinstance(v, (int, float, str)) else v
                for k, v in attrs.items()
                if k != "COMMENT"
            }
        )
        arr.attrs["_ARRAY_DIMENSIONS"] = ["z", "y", "x"][-len(shape) :]
        loc = hdu.fileinfo()["datLoc"]
        parts = ".".join(["0"] * len(shape))
        out[f"{name}/{parts}"] = [url, loc, length]
    if isinstance(out, LazyReferenceMapper):
        out.flush()
    return out, attrs


# %% ../../nbs/euclid/xarray.ipynb 7
def create_zarr_ref_from_fits(fns, out_path=None, progress=False):
    """Create a zarr reference from a set of Euclid fits files.

    This uses kerchunk to build a zarr reference file for accessing data directly from fits files.
    The resulting reference can then be opened as a xarray Dataset with `open_zarr_ref_as_dataset`.
    """
    if isinstance(fns, str):
        fns = [fns]
    else:
        fns = [str(fn) for fn in fns]
    fn = fns[0]
    if "MER" in str(fn):
        product_id_name = "tile_index"
        get_product_id = get_tile_index_from_filename
    else:
        product_id_name = "observation_id"
        get_product_id = get_obs_id_from_filename
    with fits.open(fn) as hdul:
        exts = list(h.name for h in hdul if h.size > 0)
    ref_files = []
    product_ids = []
    dither_ids = []
    filters = []
    wcs_list = []
    zp_list = []
    pbar = tqdm(fns) if progress else fns
    for fn in pbar:
        hdul = fits.open(fn, do_not_scale_image_data=True)
        product_id = get_product_id(fn)
        product_ids.append(product_id)
        dither_id = get_dither_id_from_filename(fn)
        if dither_id is not None:
            dither_ids.append(dither_id)
        filter = get_filter_from_filename(fn)
        filters.append(filter)
        if progress:
            pbar.set_description(
                f"{fn.split('/')[-1]}, {product_id}, {dither_id}, {filter}"
            )
        ref_exts = []
        coords = []
        coord_name = "extension"
        for ext in exts:
            hdu = hdul[ext]
            ext_type = _get_ext_type(ext)
            out, hdr = process_file(fn, hdu=hdu, extension=ext)
            if ext_type is not None:
                out = _rename(out, ext_type)
                coord_name = "detector"
            ref_exts.append(out)
            coord = _get_ext_det(ext)
            coords.append(coord)
            wcs = {
                k: hdr[k]
                for k in (
                    "CTYPE1",
                    "CTYPE2",
                    "CD1_1",
                    "CD1_2",
                    "CD2_1",
                    "CD2_2",
                    "CRPIX1",
                    "CRPIX2",
                    "CRVAL1",
                    "CRVAL2",
                    "NAXIS1",
                    "NAXIS2",
                )
            }
            wcs[coord_name] = coord
            if dither_id is not None:
                wcs["dither"] = dither_id
            if dither_id is not None:
                wcs[product_id_name] = product_id
            wcs_list.append(wcs)
            zp = {"ZP": hdr.get("ZPAB")}
            zp[coord_name] = coord
            if dither_id is not None:
                zp["filter"] = filter
            if dither_id is not None:
                zp["dither"] = dither_id
            if dither_id is not None:
                zp[product_id_name] = product_id
            zp_list.append(zp)
        mzz = MultiZarrToZarr(
            ref_exts,
            coo_map={coord_name: coords},
            concat_dims=[coord_name],
            identical_dims=["x", "y"],
        )
        ref_exts = mzz.translate()
        ref_files.append(ref_exts)
        hdul.close()
    coo_map = {}
    concat_dims = []
    if len(np.unique(product_ids)) > 0:
        coo_map[product_id_name] = product_ids
        concat_dims.append(product_id_name)
    if len(np.unique(dither_ids)) > 0:
        coo_map["dither"] = dither_ids
        concat_dims.append("dither")
    if len(np.unique(filters)) > 0:
        coo_map["filter"] = filters
        concat_dims.append("filter")
    mzz = MultiZarrToZarr(
        ref_files, coo_map=coo_map, concat_dims=concat_dims, identical_dims=["x", "y"]
    )
    with catch_warnings():
        filterwarnings(
            "ignore", "Concatenated coordinate .* contains less than expected"
        )
        ref = mzz.translate()
    wcs = pd.DataFrame(wcs_list)
    wcs = wcs.groupby([coord_name, product_id_name, "dither"]).first()
    wcs = wcs.to_xarray()
    zp = pd.DataFrame(zp_list)
    zp = zp.groupby([coord_name, product_id_name, "dither", "filter"]).first()
    zp = zp["ZP"].to_xarray()
    if out_path is not None:
        Path(out_path).mkdir(parents=True, exist_ok=True)
        with open(out_path / "ref.json", "w") as f:
            json.dump(ref, f)
        wcs.to_zarr(out_path / "wcs.zarr")
        zp.to_zarr(out_path / "zp.zarr")
    return (ref, wcs, zp)

# %% ../../nbs/euclid/xarray.ipynb 8
def open_zarr_ref_as_dataset(ref):
    """Open a zarr reference as a dask xarray Dataset."""
    ds = xr.open_dataset(
        "reference://",
        engine="zarr",
        chunks="auto",
        backend_kwargs={
            "storage_options": {
                "fo": ref,
            },
            "consolidated": False,
        },
    )
    return ds

# %% ../../nbs/euclid/xarray.ipynb 9
def open_fits_as_dataset(fns):
    """Create a zarr reference from a set of fits files and open as a dask xarray Dataset.

    If you plan to reopen the Dataset repeatedly, then is would be better to create the
    JSON reference once with `create_zarr_ref_from_fits`, save it, and then just open
    the reference as needed with `open_zarr_ref_as_dataset`.
    """
    ref, wcs, zp = create_zarr_ref_from_fits(fns)
    ds = open_zarr_ref_as_dataset(ref)
    return ds, wcs, zp

# %% ../../nbs/euclid/xarray.ipynb 10
def write_da_to_fits(
    da,  # the DataArray, with coordinates `x`, `y`, and `detector`
    fn,  # the filename to which to write the data
    da_wcs=None,  # an optional DataArray of WCS info for each `detector`
    overwrite=False,  # should any existing file be overwritten
):
    """Write a DataArray to a FITS file."""
    hdul = HDUList(PrimaryHDU())
    if "detector" in da.coords:
        for det in da["detector"].to_numpy():
            if da_wcs is not None:
                wcs = WCS(da_wcs.sel(detector=det).as_numpy().to_pandas())
                hdr = wcs.to_header()
            else:
                hdr = None
            hdul.append(ImageHDU(da.sel(detector=det), name=det, header=hdr))
    else:
        if da_wcs is not None:
            wcs = WCS(da_wcs.as_numpy().to_pandas())
            hdr = wcs.to_header()
        else:
            hdr = None
        hdul.append(ImageHDU(da, header=hdr))
    hdul.writeto(fn, overwrite=overwrite)
    return hdul

# %% ../../nbs/euclid/xarray.ipynb 11
def load_zarr_ref(path):
    with open(path / "ref.json") as f:
        ref = json.load(f)
    wcs = xr.open_zarr(path / "wcs.zarr")
    zp = xr.open_zarr(path / "zp.zarr")
    return ref, wcs, zp

# %% ../../nbs/euclid/xarray.ipynb 12
def _parse_wcs_dataset(wcs):
    """Parse a WCS Dataset into a DataArray of WCS objects."""
    wcs_objects = wcs.to_dataframe().apply(WCS, axis="columns")
    return wcs_objects


def load_wcs_from_zarr(fn):
    """Load a WCS Dataset from a zarr reference file."""
    wcs = xr.open_dataset(fn, engine="zarr")
    wcs = _parse_wcs_dataset(wcs)
    return wcs

# %% ../../nbs/euclid/xarray.ipynb 13
def create_all_zarr_refs(path, zarr_path, obs_id_glob="[23]*"):
    obs_ids = sorted([p.name for p in (path).glob(obs_id_glob)])
    for obs_id in obs_ids:
        fns = sorted([str(p) for p in (path / obs_id).glob("*.fits")])
        zarrfn = zarr_path / f"{obs_id}"
        if not zarrfn.exists():
            try:
                create_zarr_ref_from_fits(fns, out_path=zarrfn)
            except Exception as e:
                print(f"Error creating zarr ref for {obs_id}: {e}")
                continue

# %% ../../nbs/euclid/xarray.ipynb 14
def read_all_zarr_refs(zarr_path, obs_id_glob="[23]*"):
    ref_files = [str(p) for p in zarr_path.glob(f"{obs_id_glob}/ref.json")]
    datasets = [open_zarr_ref_as_dataset(ref) for ref in ref_files]
    ds = xr.concat(datasets, dim="observation_id")
    ds = ds.assign_coords(y=("y", ds.y.values), x=("x", ds.x.values))
    wcs_files = [str(p) for p in zarr_path.glob(f"{obs_id_glob}/wcs.zarr")]
    wcs = xr.open_mfdataset(wcs_files, engine="zarr", combine="nested", concat_dim="observation_id")
    zp_files = [str(p) for p in zarr_path.glob(f"{obs_id_glob}/zp.zarr")]
    zp = xr.open_mfdataset(zp_files, engine="zarr", combine="nested", concat_dim="observation_id")
    return ds, wcs, zp

# %% ../../nbs/euclid/xarray.ipynb 15
def xr_fast_mask(
    data,
    mask_params=None,  # mask parameters
    estimate_background=False,  # estimate the background from the image median
    max_repeat=10,  # maximum number of masking iterations
    relative_rms_tolerance=0.01,
    verbose=False,
):
    mask = xr.apply_ufunc(
        fast_mask,
        data,
        kwargs=dict(
            mask_params=mask_params,
            estimate_background=estimate_background,
            max_repeat=max_repeat,
            relative_rms_tolerance=relative_rms_tolerance,
            verbose=verbose,
            return_threshold=False,
        ),
        vectorize=True,
        dask="parallelized",
        input_core_dims=[["x", "y"]],
        output_core_dims=[["x", "y"]],
        output_dtypes=[bool],
    )
    return mask
