[DEFAULT]
# All sections below are required unless otherwise specified.
# See https://github.com/fastai/nbdev/blob/master/settings.ini for examples.

### Python library ###
repo = nicl
lib_name = %(repo)s
version = 0.0.1
min_python = 3.7
license = apache2
black_formatting = False

### nbdev ###
doc_path = _docs
lib_path = nicl
nbs_path = nbs
recursive = True
tst_flags = notest
put_version_in_init = True

### Docs ###
branch = main
custom_sidebar = False
doc_host = https://%(user)s.github.io
doc_baseurl = /%(repo)s
git_url = https://github.com/%(user)s/%(repo)s
title = %(lib_name)s

### PyPI ###
audience = Developers
author = Steven Bamford
author_email = steven@stevenbamford.com
copyright = 2023 onwards, %(author)s
description = New Nottingham ICL code
keywords = nbdev jupyter notebook python
language = English
status = 3
user = IntraClusterLight

### Optional ###
requirements = astropy astroquery dask dask-image FyeldGenerator galsim kerchunk matplotlib memory_profiler numpy photutils pointpats pyyaml regions reproject scikit-image scipy shapely sigfig spherical-geometry tqdm xarray
dev_requirements = ipykernel ipywidgets nbdev nbdime nbqa notebook pre-commit ruff setuptools
# console_scripts =