# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/hsc/01_hsc_preparation.ipynb.

# %% auto 0
__all__ = ['fields', 'get_f21_table2', 'fetch_cluster_cutout', 'make_xcs_filename', 'fetch_f21_cluster_cutout',
           'fetch_all_f21_cluster_cutouts', 'f21_cluster_image', 'hsc_query', 'fetch_galaxy_catalogue', 'fetch_tracts']

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 6
import astropy.cosmology.units as cu
import astropy.units as u
from astropy.table import QTable
from importlib_resources import files


def get_f21_table2():
    """Get the XSC cluster properties from Furnell et al. (2021) as a QTable."""
    fn = files("nicl.data.hsc").joinpath("furnell21_table2.tex")
    tab = QTable.read(
        fn,
        format="ascii.latex",
        units=[None, u.deg, u.deg, cu.redshift, u.ABmag]
        + [u.keV] * 3
        + [u.Mpc] * 3
        + [10**14 * u.Msun] * 3,
    )
    return tab

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 9
from ..hsc_utils.downloadCutout import Rect, download


def fetch_cluster_cutout(name, ra, dec, radius, filter, hsc_user, hsc_password):
    """Fetch a HSC-SSP image of a cluster and save to disk.

    Parameters
    ----------
    name : str
        Filename in which to save the downloaded image.
    ra : float
        RA coordinate of the cluster centre, in degrees.
    dec : float
        Dec coordinate of the cluster centre, in degrees.
    radius : float
        The half-size of the cutout image, in degrees.
    filter : str
        The filter to fetch, e.g. "i".
    hsc_user : str
        The user of the HSC website account used to access the data.
    hsc_password : str
        The password of the HSC website account used to access the data.

    """
    rect = Rect.create(
        rerun="pdr3_dud_rev",
        type="coadd/bg",
        filter=filter,
        ra=ra,
        dec=dec,
        sw=radius,
        sh=radius,
        image=True,
        mask=True,
        variance=True,
        name=name,
    )
    download(rect, user=hsc_user, password=hsc_password, onmemory=False)

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 10
from os.path import join

def make_xcs_filename(xcs_id, filter, data_path):
    """Construct the filename (without extension) for a given `xcs_id` and `filter`."""
    xcs_id = xcs_id.replace(" ", "_")
    return join(data_path, f"{xcs_id}/{xcs_id}_{filter}")

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 11
from os.path import exists

from astropy.cosmology import FlatLambdaCDM


def fetch_f21_cluster_cutout(
    xcs_id, filter, hsc_user, hsc_password, data_path, overwrite=False
):
    """Fetch a HSC-SSP image of an F21 cluster and save to disk.

    Parameters
    ----------
    xcs_id : floats
        XCS ID of the cluster.
    filter : string
        The filter to fetch, e.g. "i".
    hsc_user, hsc_password : strings
        The user and password of the HSC website account used to access the data.
    data_path : string
        The folder in which to store the downloaded images.
    overwrite : bool, default False
        Force overwriting of existing files.

    """
    f21_clusters = get_f21_table2()
    cluster = f21_clusters[f21_clusters["XCS ID"] == xcs_id][0]
    name = make_xcs_filename(xcs_id, filter, data_path)
    if overwrite or not exists(f"{name}.fits"):
        ra = cluster["ra"].to_value("deg")
        dec = cluster["dec"].to_value("deg")
        z = cluster["z"]
        cosmo = FlatLambdaCDM(H0=70, Om0=0.3)
        deg_per_Mpc = 1 / cosmo.kpc_proper_per_arcmin(z).to(u.Mpc / u.deg)
        radius = (1.5 * cluster["R_X"] * deg_per_Mpc).to_value("deg")
        fetch_cluster_cutout(name, ra, dec, radius, filter, hsc_user, hsc_password)

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 12
def fetch_all_f21_cluster_cutouts(hsc_user, hsc_password, data_path, overwrite=False):
    """Save HSC-SSP grizy images of all F21 clusters to disk.

    Parameters
    ----------
    hsc_user, hsc_password : strings
        The user and password of the HSC website account used to access the data.
    data_path : string
        The folder in which to store the downloaded images.
    overwrite : bool, default False
        Force overwriting of existing files.

    """

    f21_clusters = get_f21_table2()
    for xcs_id in f21_clusters["XCS ID"]:
        print(xcs_id, end=": ")
        for filter in "grizy":
            print(filter, end="")
            fetch_f21_cluster_cutout(
                xcs_id, filter, hsc_user, hsc_password, data_path, overwrite
            )
        print()

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 19
from astropy.nddata import CCDData

def f21_cluster_image(xcs_id, filter, data_path, return_hdus=False):
    fn = make_xcs_filename(xcs_id, filter, data_path) + ".fits"
    print(fn)
    img = CCDData.read(fn, unit="adu", hdu=1)
    mask = CCDData.read(fn, unit=u.dimensionless_unscaled, hdu=2)
    sigma = CCDData.read(fn, unit="adu", hdu=3)
    return img, mask, sigma

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 25
fields = dict(XMMLSS=[33.5, 38, -6.5, -3] * u.deg,
              COSMOS=[148, 152, 0.5, 4] * u.deg,
              ELAISN1=[240, 246, 53, 57] * u.deg,
              DEEP23=[350, 354.5, -2, 1.5] * u.deg)

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 26
import nicl.hsc_utils.hscReleaseQuery as hrq

def hsc_query(credential, sql, outfn, format="csv"):
    """Perform an SQL query on the HSC CAS database."""
    job = hrq.submitJob(credential, sql, out_format=format)
    hrq.blockUntilJobFinishes(credential, job['id'])
    with open(outfn, 'wb') as outfile:
        hrq.download(credential, job['id'], outfile)
    hrq.deleteJob(credential, job['id'])

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 27
def fetch_galaxy_catalogue(field, bounds, hsc_user, hsc_password, data_path, overwrite=False):
    """Download the galaxy catalogue for the specified `field`."""
    credential = {"account_name": hsc_user, "password": hsc_password}
    field_cat_sql = """
    SELECT f.object_id, ra, dec,
    g_kronflux_mag, g_kronflux_magerr, r_kronflux_mag, r_kronflux_magerr, i_kronflux_mag, i_kronflux_magerr,
    z_kronflux_mag, z_kronflux_magerr, y_kronflux_mag, y_kronflux_magerr, 
    photoz_best, photoz_risk_best, photoz_std_best, specz_redshift, specz_redshift_err
    FROM pdr3_dud_rev.forced as f
    JOIN pdr3_dud_rev.forced2 USING (object_id)
    JOIN pdr3_dud.photoz_dnnz USING (object_id)
    LEFT JOIN pdr3_dud_rev.specz USING (object_id)	
    WHERE boxSearch(coord, {}, {}, {}, {});
    """
    outfn = join(data_path, f"{field}_cat.fits")
    if overwrite or not exists(outfn):
        sql = field_cat_sql.format(*bounds.to_value("deg"))
        hsc_query(credential, sql, outfn, format="fits")

# %% ../../nbs/hsc/01_hsc_preparation.ipynb 32
def fetch_tracts(field, bounds, hsc_user, hsc_password, data_path, overwrite=False):
    """Download the galaxy catalogue for the specified `field`."""
    credential = {"account_name": hsc_user, "password": hsc_password}
    tract_sql = """
    SELECT DISTINCT tract
    FROM pdr3_dud_rev.mosaic
    WHERE mosaic.areacube && cube_from_radecrange({}, {}, {}, {});
    """
    outfn = join(data_path, f"{field}_tracts.csv")
    if overwrite or not exists(outfn):
        sql = field_cat_sql.format(*bounds)
        hsc_query(credential, sql, outfn)
