"""Data preparation for a [worked example](05_hsc_analysis.ipynb) of analysing the ICL in images from the HSC-SSP deep survey."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/hsc/01_hsc_preparation.ipynb.

# %% auto #0
__all__ = ['fields', 'get_f21_table2_original', 'get_f21_table2', 'make_xcs_filename', 'f21_cluster_image', 'find_field']

# %% ../../nbs/hsc/01_hsc_preparation.ipynb #fa8840aa-068a-405e-8e18-079c9d149f77
from os.path import join

import astropy.cosmology.units as cu
import astropy.units as u
from astropy.nddata import CCDData
from astropy.table import QTable
from importlib.resources import files

from ..utilities import physical_to_angular

# %% ../../nbs/hsc/01_hsc_preparation.ipynb #1e31e463-c906-4bda-b98e-41e26e622fdb
def get_f21_table2_original():
    """Get the XSC cluster properties from Furnell et al. (2021) as a QTable."""
    fn = files("nicl.data.hsc").joinpath("furnell21_table2.tex")
    tab = QTable.read(
        fn,
        format="ascii.latex",
        units=[None, u.deg, u.deg, cu.redshift, u.ABmag]
        + [u.keV] * 3
        + [u.Mpc] * 3
        + [10**14 * u.Msun] * 3,
    )
    return tab


def get_f21_table2():
    """Get the XSC cluster properties from Furnell et al. (2021) as a QTable.

    Include some additional calculated columns for convenience.
    """
    tab = get_f21_table2_original()
    tab["R_X_arcsec"] = physical_to_angular(tab["R_X"], tab["z"]).to(u.arcsec)
    return tab

# %% ../../nbs/hsc/01_hsc_preparation.ipynb #228b6dc4-d1bd-413e-b534-ff533283573b
def make_xcs_filename(xcs_id, filter, data_path):
    """Construct the filename (without extension) for a given `xcs_id` and `filter`."""
    xcs_id = xcs_id.replace(" ", "_")
    return join(data_path, f"{xcs_id}/{xcs_id}_{filter}")

# %% ../../nbs/hsc/01_hsc_preparation.ipynb #b7b9e930-37c2-4494-a82c-0d4e9557541d
def f21_cluster_image(xcs_id, filter, data_path, return_hdus=False):
    fn = make_xcs_filename(xcs_id, filter, data_path) + ".fits"
    print(fn)
    img = CCDData.read(fn, unit="adu", hdu=1)
    mask = CCDData.read(fn, unit=u.dimensionless_unscaled, hdu=2)
    sigma = CCDData.read(fn, unit="adu", hdu=3)
    return img, mask, sigma

# %% ../../nbs/hsc/01_hsc_preparation.ipynb #d25699e8-e7f8-4099-b721-1c314e266a7f
fields = dict(
    XMMLSS=[33.5, 38, -6.5, -3] * u.deg,
    COSMOS=[148, 152, 0.5, 4] * u.deg,
    ELAISN1=[240, 246, 53, 57] * u.deg,
    DEEP23=[350, 354.5, -2, 1.5] * u.deg,
)


def find_field(coord):
    for f, bounds in fields.items():
        ra_low, ra_high, dec_low, dec_high = bounds
        if (
            (ra_low < coord.ra)
            and (coord.ra < ra_high)
            and (dec_low < coord.dec)
            and (coord.dec < dec_high)
        ):
            return f
