sbatch stack.py I standard
sbatch stack.py Y standard
sbatch stack.py J standard
sbatch stack.py H standard
sbatch stack.py I mer
sbatch stack.py Y mer
sbatch stack.py J mer
sbatch stack.py H mer
sbatch stack.py I no_processing
sbatch stack.py Y no_processing
sbatch stack.py J no_processing
sbatch stack.py H no_processing
sbatch stack.py I no_bkg_match
sbatch stack.py Y no_bkg_match
sbatch stack.py J no_bkg_match
sbatch stack.py H no_bkg_match
sbatch stack.py I no_skyflat
sbatch stack.py Y no_skyflat
sbatch stack.py J no_skyflat
sbatch stack.py H no_skyflat
sbatch stack.py Y no_tartan
sbatch stack.py J no_tartan
sbatch stack.py H no_tartan
sbatch stack.py Y no_persistence
sbatch stack.py J no_persistence
sbatch stack.py H no_persistence
